### ISSUE TITLE
Rationnel dans les propositions glisser-déposer

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#10]
Est-il possible qu'un glisser-déposer affiche 1/3 au lieu de 0,3333333333 ?

<img width="920" alt="isyro" src="https://user-images.githubusercontent.com/105806953/170363479-2516acea-7678-412e-b15c-66c1540641d2.PNG">

**Comment by benoitkugler** [comment]
Il me semble que c'est un cas où il faut écrire dans le champ de réponse directement &w/z&.

Peut être que c'est un cas où on a besoin de pouvoir définir des paramètres aléatoires qui restent des expressions, qui ne sont pas évaluées (sauf nécessité).
Ca permet de réutiliser deux fois la même expression sans avoir à la re taper.

**Comment by Guigui7707** [comment]
En effet ! Merci beaucoup ! Et désolé du dérangement du coup..
