### ISSUE TITLE
Bug ? exercice, paramètres liés

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#100]
J'ai importé une question pour créer un exercice, mais en basculant tous les paramètres en violet ça me met un message d'erreur. Pourtant rien n'a changé, je ne vois pas.. (mais j'ai l'impression que l'exercice valide ma réponse si elle est juste).
<img width="502" alt="isyro" src="https://user-images.githubusercontent.com/105806953/183254964-48a7b24e-30f8-44e4-89df-1a95011c726a.PNG">

**Comment by benoitkugler** [comment]
Ah, intéressant ! 
C'est un problème un peu subtil : comme la question est importée, elle n'utilise pas les paramètres de l'exercice.
Comme r est passé en partagé, il a disparu des paramètres personnels de la question.

A discuter en lien avec #105 , qui devrait simplifier la situation et éviter ce problème.
