### ISSUE TITLE
[questions] Création nouveau bloc réponse Equation cartésienne

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#101]
Sur le même principe que le bloc créé pour accepter plusieurs réponses quand on demande un vecteur colinéaire à un autre, il faudra pouvoir accepter à terme les nombreuses équations cartésiennes d'une même droite

**Comment by Guigui7707** [comment]
+ un autre bloc qui gère la trigonométrie : acceptation des réponses avec un choix de 2Pi près ou par exemple 120° et 240° accepté (pour un angle recherché avec le cosinus de donné)

**Comment by Guigui7707** [comment]
+ un bloc énoncé pour le cercle trigo (ou plutôt ajout d'un cercle dans les options de figures)

**Comment by benoitkugler** [comment]
> Sur le même principe que le bloc créé pour accepter plusieurs réponses quand on demande un vecteur colinéaire à un autre, il faudra pouvoir accepter à terme les nombreuses équations cartésiennes d'une même droite

Ajouter une option "à coefficient près" sur le champ Expression

**Comment by Guigui7707** [comment]
Super class !!
Juste dans l'aide en sélectionnant le mode "équation linéaire" n'est-ce pas plutôt "équation cartésienne" qu'il faudrait écrire ?

**Comment by Guigui7707** [comment]
@benoitkugler
