### ISSUE TITLE
[eleve] Détails notation élève

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#102]
Je ne sais pas si on en a discuté mais pouvoir afficher les réponses avec une virgule (surtout sur l'écran élève lorsqu'il clique sur "afficher la réponse" lors du décrassage ou quand il consultera la réponse d'un travail à la maison, ce serait bien qu'il voit 12,25 et pas 12.25 pour éviter les confusions . et virgule (notation anglaise pour le séparateur des milliers)
<img width="212" alt="isyro" src="https://user-images.githubusercontent.com/105806953/183278965-d963822f-e9f0-4a1e-b858-f6a6b2bfc326.PNG">

**Comment by benoitkugler** [comment]
Ah oui bien vu. En fait on accepte déjà la virgule dans les entrées, mais on ne l'utilise en effet pas dans les sorties.
