### ISSUE TITLE
[questions] Variables sur légende fonctions

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#109]
Je ne retrouve plus d'issue à ce sujet (j'avais demandé pour la réponse élève, là c'est pour l'affichage bloc graphe de fonction).
ça permettrait que le nombre dérivé ne soit pas toujours à lire sur la tangente T1 :)

**Comment by Guigui7707** [comment]
A voir si c'est judicieux, mais ajouter un point sur un graphe de fonction (bloc énoncés) pourrait être utile pour les tangentes à une fonction en un point.

**Comment by benoitkugler** [comment]
Est-ce que dans ce cas il ne faut pas carrément proposer le tracé de tangente ? 
Il y aurait d'autres utilisations du point seul ?

**Comment by benoitkugler** [comment]
Ajouter une liste de points (légende (avec interpolation), fonction, abscisses).
