### ISSUE TITLE
Réponse élève : construire une droite verticale

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#11]
Comment s'y prendre pour que l'élève construise une droite verticale de la forme x=c ?
Pas par les fonctions affines, mais pas par une réponse "points" non plus...
<img width="929" alt="isyro" src="https://user-images.githubusercontent.com/105806953/170368263-9b6f0554-c131-46dd-8b16-36ad95e842d3.PNG">

**Comment by benoitkugler** [comment]
Je propose d'accepter la valeur Inf (pour infini) dans la case A, avec la convention que quand A = Inf, B contient l'abscisse (c) de la droite verticale.
Ce n'est qu'à moitié cohérent mathématiquement (B n'a pas de sens si A = Inf), mais ça permet de garder la même interface.

**Comment by benoitkugler** [comment]
Ajouter de la documentation
Renommer le block en Droite
