### ISSUE TITLE
[questions] Expression : aide aux fractions

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#110]
A discuter : pour éviter que l'élève n'écrive la fraction (2x+3)/(x+1) permettre d'utiliser un bloc réponses fraction directement intégré dans une fraction avec deux expressions à rentrer pour l'élève (le numérateur et le dénominateur). Besoin pour les questions intermédiaires d'un exercice lié pour trouver le taux d'accroissement entre a et a+h par exemple.
Bien sûr si l'élève n'est pas sûr de tomber sur une fraction le mieux est de le laisser avec le champ "expression" existant + indication en italique quand la question est codée de la nomenclature des fractions.

**Comment by benoitkugler** [comment]
On est d'accord que ce qui t'embête c'est la syntaxe requise par / (les parenthèses notamment) pour l'élève ?
Si on allait dans ce sens, je préférerais une option sur le bloc expression : une case à cocher "Aide aux fractions". Si elle est activée, et que la réponse est vraiment une fraction,  le champ de réponse affiche ce que tu as proposé.
