### ISSUE TITLE
Bug bloc réponses tableau de signes (variables non acceptées)

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#111]
Bien que l'indication le stipule, &x_1& n'est pas reconnue comme réponse reconnue dans la ligne des x

**Comment by Guigui7707** [comment]
Juste si jamais tu as un moment (sinon aucun soucis, moi je n'ai pas de moment avant fin septembre vois-tu xD) je relance celui-ci puisque mes premières arrivent sur Delta la semaine prochaine donc tableau de signes aussi :)

**Comment by benoitkugler** [comment]
Merci pour la relance :)

Le problème principale venait du fait que les variables n'était pas remplacées par leur valeur. C'est corrigé.
Il reste un problème d'ergonomie : les champs acceptent une seule expression, et pas un texte libre. Donc la syntaxe ici est d'enlever les & &, mais ce n'est pas ce que suggère le champ actuel. On devrait utiliser le même champ que celui des tableaux de variations. 
Comme tu as une solution simple, je corrigerai ce problème plus tard (et je laisse ce fil ouvert).
