### ISSUE TITLE
[prof/editor] Symbol Pi

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#113]
Utiliser le mot pi à la place du symbol Unicode.

Améliorer l'affichage des fractions de la forme +- n pi / m (voir les questions Associer le réel au point du cercle trigo).

**Comment by benoitkugler** [comment]
@Guigui7707 Concernant la question Associer le réel au point du cercle trigonométrique, je ne retrouve plus d'exemple où une fraction du type n*pi/m s'affiche bizarrement. Pourrais-tu reconstruire un exemple d'utilisation problématique ?

**Comment by Guigui7707** [comment]
@benoitkugler hum.. je regarde depuis tout à l'heure mais j'ai du mal à retrouver :/
En fait je pense que c'était pour faire 3 questions au lieu des 12 que j'ai faite sur celle-ci. Peut-être que mes fractions se simplifiaient automatiquement ou je ne sais.
Me rappelant que je n'en avais pas fais une issue Github (je te l'avais mentionné à l'oral) car cette question est très spécifique à ce chapitre de trigo, peut-être peut-on laisser tomber en attendant que je rencontre cette problématique plus tard en codant ? A ce moment-là je ferais une capture d'image claire du truc pour une intervention plus efficace, si ça te va ?

**Comment by benoitkugler** [comment]
Parfait !
Je ferme donc l'issue pour le moment.
