### ISSUE TITLE
[prof/editor] Possibilité de dupliquer une question d'un exercice

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#116]
Possibilité de dupliquer un exercice complet (ex : utile pour les cas du signe de Delta, 3 exercices de fait sur le même modèle)

_Originally posted by @Guigui7707 in https://github.com/benoitkugler/maths-online/issues/92#issuecomment-1197936134_

**Comment by benoitkugler** [comment]
@Guigui7707 Est-ce que cette nouvelle fonctionnalité est toujours d'actualité ? Ou est-ce que la duplication actuelle d'une *variante* suffit ?

**Comment by Guigui7707** [comment]
En fait on pourrait s'en passer simplement si on peut dupliquer la dernière question d'un exercice (puisque l'exercice se suit). Seulement en créant l'exercice d'exemple je me suis aperçu qu'il est possible de dupliquer une question créée d'un exercice créé via l'onglet "variantes" mais que celle-ci n'apparaît pas ni dans l'exercice en cours (en tant que question suivante) ni dans la base de questions pour pouvoir ensuite l'importer (en tout cas impossible de nommer les questions créées à l'intérieur d'un exercice).

**Comment by Guigui7707** [comment]
@benoitkugler

**Comment by benoitkugler** [comment]
Après discussion, il s'agit surtout de pouvoir dupliquer une question à l'intérieur d'une variante.
