### ISSUE TITLE
Interface élèves : info bandeau joueurs

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#12]
Laisser le bandeau "à Pauline de lancer le dé" visible plus longtemps (si possible jusqu'au moment où le dé est lancé), idem pour "Pauline déplace le pion" et "Pauline est entrain de choisir la case".
(Par retour d'expérience elle attendait car elle ne savait pas que c'était à elle de lancer le dé ^^)

**Comment by Guigui7707** [comment]
Oups en fait en laissant le bandeau ça caché le dé =D donc laisse comme ça je pense que c'est galère sinon ça ferait couper le bandeau ou monter le dé c'est pas ouf

**Comment by benoitkugler** [comment]
Prolonger la durée. 
Ajouter un bouton pour masquer le bouton.
