### ISSUE TITLE
[eleve] Affichage question longue bloquante écran élève

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#124]
Sur mon écran l'expression à factoriser (3x+13)(5x-7)+(3x+13)(6x-12) dépasse et je ne vois pas (6x-12)avec impossibilité de décaler vers la droite pour voir la suite. Du coup dans un exercice lié pas moyen de passer à la suivante si ce n'est en relançant la question jusqu'à en avoir une plus courte du style (x+1)(x-7)+(x+1)(x-8)

**Comment by benoitkugler** [comment]
@Guigui7707 J'ai corrigé le problème sur les "moules" Texte et Expression, peux-tu confirmer que c'est bien là qu'était le souci ?
