### ISSUE TITLE
[questions] aide à la notation isyro

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#128]
Une idée serait de forcer le prof qui code une question à décocher (ou cocher) "aide notation isyro" qui serait un bloc texte déjà intégré automatiquement à la création d'une question, mais qui resterait "en bas" de l'exercice sans gêner l'ajout de bloc...
Dans l'optique d'alerter le prof systématiquement sur le fait de peut-être devoir aider ses élèves afin qu'ils ne bloquent pas sur la partie notation isyro et qu'ils puissent se concentrer sur les maths uniquement.

**Comment by benoitkugler** [comment]
Voir aussi #90

**Comment by benoitkugler** [comment]
Remplacée par #90
