### ISSUE TITLE
[prof/editor] fonction isMultiple

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#135]
Pas pour tout de suite, rien d'urgent :
une fonction isMultiple (un truc du genre) qui renvoie 1 si le reste de la division de A par B est 0, 0 sinon. Serait utile !

Pour l'exemple, cela me permettrait de m'assurer qu'une moyenne pondérée est toujours une valeur approchée pour sélectionner uniquement le "environ" dans le menu déroulant d'une des réponses ; ou mieux encore, de sélectionner automatiquement le "environ" ou le "égal" suivant la situation pour une seule et même question.
Pour le moment je me contente aisément d'infléchir les probas vers zéro :) (une division par 71, 72, 73, 74 ou 75 tombera rarement sur une valeur exacte =D)

**Comment by benoitkugler** [comment]
Si je ne me trompe pas c'est déjà possible à l'aide des opérateurs % et //  : 
A % B renvoie le reste de la division de A par B, donc ce que tu voulais s'écrit A % B == 0 
// renvoie le quotient *entier* de la division de A par B

Ces deux opérateurs n'étaient pas documentés, je les ajoute.

**Comment by Guigui7707** [comment]
Oui c'est parfait ! Merci je n'avais pas su pour les opérateurs % et //, ils font très bien l'affaire !
@benoitkugler
