### ISSUE TITLE
[prof] Curseur liste de questions, exercices

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#137]
Simplement, quand la souris passe sur un titre de question la souris est comme le curseur sur Word et plus comme avant (mais j'ai oublié comment c'était, sûrement une souris en surbrillance ou une souris qui passe en forme de main, ou la question en fond grisé ?) Cela montre que c'était parfait car je m'en rappelle plus xD

**Comment by benoitkugler** [comment]
Bien vu !

**Comment by benoitkugler** [comment]
(Conséquence d'un changement de la librairie utilisée)
