### ISSUE TITLE
[prof] Conseil de création d'un triv'maths

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#138]
Après réflexion toujours plus fine, je pense qu'une bonne utilisation du triv'maths se concentre sur des questions rapide ou de base. Cela permet de régler une question à 90 secondes afin de rythmer les parties et tourner sur plus de questions, de mettre de la fluidité et dynamique dans une partie. Pour une bonne expérience de jeu !
Cela implique de mettre de côté du triv'maths les questions difficiles ou qui prennent beaucoup de temps.
Cela entraîne en cascade de régler les étiquettes au moment des créations de questions !

Ainsi je propose d'ajouter un point d'interrogation à côté de la création d'un triv'maths ou une intro en haut ; idem à côté des étiquettes au moment où l'on veut ajouter. Du style :

"**Conseil** d'utilisation de triv'maths : ne pas intégrer de questions trop longues et/ou question de type problème ouvert, les réserver pour le travail à maison"
"**Conseil** d'utilisation d'étiquettes : mettre ici la classe, puis deux étiquettes maximum (chapitre et spécificité) afin de simplifier la création de triv'maths ; pour les questions longues et/ou de types problème ouvert, remplacer la spécificité par une étiquette 'problème ouvert' afin de les exclure judicieusement d'une partie de triv'maths"

OU ALORS (pour le deuxième conseil) : permettre dans la création d'un triv'maths d'exclure des questions comporter telle étiquette sélectionnée. Ainsi on peut simplement demander d'ajouter une troisième étiquette "problème ouvert" pour pouvoir ensuite les exclure si besoin du triv'maths.

Voilà, tu me diras ce que tu en penses, rien de pressant.

**Comment by benoitkugler** [comment]
Prévoir d'exclure une catégorie.

En attente de #147
