### ISSUE TITLE
Petits bugs résiduels contournables de la v.0.9

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#140]
Lorsqu'il n'y a qu'une seule variante dans une question, impossible de la coter en difficulté ou de la sous-titrée. Dès qu'il y a une deuxième c'est bon.

A l'import d'une variante dans un nouvelle question elle s'affiche, puis en la dupliquant pour importer une nouvelle elle marche aussi mais en revenant sur la première importée c'est vide : en réimportant une deuxième fois celle-ci ça passe pour de bon ensuite.

**Comment by benoitkugler** [comment]
Alors en fait le comportement est voulu, avec l'idée que, s'il n'y a qu'une variante, on ne veut probablement pas la "différencier".
Et ça permettait d'alléger l'éditeur pour en rendant moins envahissant les variantes. Mais bon.. on peut revenir comme avant.
Je vais voir si je trouve une meilleure approche pour ça : l'idée étant de penser à l'utilisation en mode "mono variante" qui sera peut être la plus courante pour les nouveaux utilisateurs.

**Comment by benoitkugler** [comment]
Remarque au passage : pour l'utilisation dans l'activité Travail à la maison, ça semblerait assez cohérent de vouloir ajouter toutes les variantes d'une question. On peut déjà le faire manuellement mais ça vaudrait peut-être le coup d'ajouter un raccourci pour ? (Idem pour les exercices).
Je pense à l'utilisateur "casual" qui veut juste profiter de la pertinente base admin.

**Comment by Guigui7707** [comment]
Bien vu :) pas besoin de différencier quand il n'y a qu'une seule variante. Comme la difficulté n'est pas possible, il faut juste s'assurer que la question apparaîtra bien dans un triv'maths donc l'auteur a sélectionné par exemple les questions "1 étoile"

Pour ta remarque oui je pense que ce sera intéressant d'ajouter d'un coup toute la question et toutes ses variantes, même si jusqu'à aujourd'hui pour ma maigre utilisation ça ne m'a jamais gêné (pas eu la nécessité je pense).

**Comment by benoitkugler** [comment]
Après réflexion, comme je n'ai pas de meilleure idée en tête, je vais juste rétablir le comportement précédent : toujours afficher le champ
