### ISSUE TITLE
[prof/homework] Bouton retour mis en valeur

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#143]
Sur les feuilles de travail, uniformiser le bouton retour ou la croix : en haut à droite à chaque fois ? (à discuter, peut-être est-ce nécessaire de mettre à deux endroits différents car boutons à fonctionnalités différentes)
Quoi qu'il en soit : mettre une couleur de fond derrière le "retour" pour qu'il soit mis en avant et capté plus facilement.

**Comment by benoitkugler** [comment]
Je propose de ne laisser qu'un seul chemin : pour les petits dialogues (style confirmation) : le bouton retour, pour les grandes fenêtres, plutôt la croix.
Donc ici, seulement la croix.

**Comment by benoitkugler** [comment]
Je propose de ne laisser qu'un seul chemin : pour les petits dialogues (style confirmation) : le bouton retour, pour les grandes fenêtres, plutôt la croix.
Donc ici, seulement la croix.
