### ISSUE TITLE
Option nombre de solutions comme pour les tableaux de variations et les arbres de probas

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#145]
Actuellement coder un exercice qui demande la résolution d'une équation se heurte à un choix systématique : 
- soit on code en faisant apparaître à l'avance le nombre de réponse (ex : S={ ... }) l'élève complète mais il sait d'avance qu'il n'y a qu'une seule solution ; ou S={... ; ...} là il sait qu'il y en a deux
- soit on code avec la liste ordonnée mais cette fois-ci l'élève connaît les valeurs proposées donc il peut juste vérifier lesquelles sont solutions (bon en en mettant plein il va être dissuadé)

Est-ce que ce serait judicieux de lui proposer un choix à l'avance : combien de solutions ? Et cela le dirige vers une réponse pré-enregistrée du type S={...} ou S={...;...}. Ou encore mieux pour être parfait, du type : QCM menu déroulant (choix : S et d'autres lettres) puis QCM menu déroulant (choix : =, environ égal, etc) puis QCM menu déroulant (choix : ( ; ) ; [ ; ] ; { ; }) puis champ à compléter (un seul s'il a répondu : une seule solution) puis QCM menu déroulant (choix : ( ; ) ; [ ; ] ; { ; }) et voilà. Sauf s'il a dit deux, alors à la place du dernier QCM menu déroulant mettre QCM menu déroulant (choix : virgule, point-virgule, point) puis champ à compléter (pour la deuxième solution s'il a mis deux solutions) puis QCM menu déroulant final (choix : ( ; ) ; [ ; ] ; { ; }).
Il pourrait voter au début pour : 0 solution, 1 solution, 2 solutions, 3 solutions, systématiquement.
Pour 0 solution ça donnerait S="ensemble vide" à choisir contre un zéro et une croix dans un QCM menu déroulant par exemple.

Après on pourrait envisager ça sur une inéquation mais c'est encore plus complexe (voter au début pour : aucune solution, une solution, deux solutions, trois solutions, une infinité de solutions puis gérer les formats mais si un jour on fait je te détaillerais).

**Comment by Guigui7707** [comment]
Resterait le hic de faire ordonner par ordre croissant les solutions ou par ordre des facteurs.
Sur Wims j'avais vu un champ de réponse où l'élève met ses solutions séparées par une virgule (foireux bien sûr la virgule, je préfère à ce moment-là la solution exposée ci-dessus) mais l'ordre n'importe pas.

**Comment by benoitkugler** [comment]
Question très pertinente, qui demande réflexion. 

Une approche différente pourrait être d'étendre la syntaxe actuelle des expressions pour supporter la notation d'ensemble.
La réponse élève devrait alors suivre la syntaxe précise`{ ... ; ... }` (je pense qu'on doit imposer `;` comme délimiteur pour éviter les confusions avec `,` déjà utilisé pour les nombres à virgule.

Un intérêt serait d'élargir les possibilités pour les autres moules.

**Comment by benoitkugler** [comment]
Après discussion : Accepter une syntaxe plus élaborée : vecteur ou ensemble
