### ISSUE TITLE
[prof] Problèmes de duplications

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#148]
Alors voici un chemin (excuse tu m'avais déjà demandé des captures d'écrans la semaine dernière sur ce sujet dsl...) qui amène à un bug :

- créer une question
- titre, étiquette et sous-titres renseignés
- création de ma question (bloc texte, bloc formule, bloc texte, bloc QCM déroulant, bloc expression, bloc texte, bloc texte)
- enregistrement
- duplication de ma question
- sous-titre modifié
- modification de la question (dans le bloc formule, un "plus" changé en "moins", dans les paramètres idem)
- enregistrement
- retour sur la première question codée : présence plus que du premier bloc texte et du bloc formule (avec le "plus" OK), tous les autres ont disparu ! Mais aussi une "remise à zéro" de tous mes paramètres : randint(1;10) au lieu de ceux que j'avais renseigné
- retour sur le duplicata modifié : le paramètre ajustée est resté ajusté, mais pas le "moins" du bloc formule : il est redevenu un "plus" (si je remodifie, enregistre, passe sur la première variante puis revient sur la nouvelle rebelote la modif a disparu)

Note : c'est la première fois que ça me la maintien à "moitié", jusque là ça me supprimait tout et il n'y avait plus rien, la possibilité de glisser un fichier json seulement.

**Comment by Guigui7707** [comment]
En sortant de la question puis en revenant les modifications viennent de s'appliquer (c'est peut-être ça qu'il faut faire : sortir systématiquement avant de poursuivre ?).

**Comment by benoitkugler** [comment]
Parfait, merci beaucoup Guillaume pour la reproduction détaillée. C'est clairement un bug en effet ! 

> c'est peut-être ça qu'il faut faire : sortir systématiquement avant de poursuivre ?

Cette étape ne devrait pas être nécessaire !
