### ISSUE TITLE
Légende variable tableau de variations et avec LaTeX

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#16]
Il faudrait que la légende sur un tableau de variation puisse être une variable (si ça ne génère pas d'autres problèmes) afin d'adapter le nom d'une fonction automatiquement et aléatoirement

<img width="922" alt="isyro" src="https://user-images.githubusercontent.com/105806953/170580181-f9294275-ba0b-403d-b20d-27ce4c0afee3.PNG">

**Comment by Guigui7707** [comment]
Idem pour le nom d'un vecteur, que la notation Latex puisse passer
![Isyro](https://user-images.githubusercontent.com/105806953/170962947-da580ff2-aff1-43fa-82da-58ef9823ba2b.PNG)

**Comment by benoitkugler** [comment]
Autoriser randLetter comme expression pour le nom des points

**Comment by Guigui7707** [comment]
OK pour les variables dans le nom d'une fonction d'un tableau de variations
OK pour le langage LateX accepté dans le nom d'un vecteur
RESTE que le nom d'un vecteur puisse être une variable

**Comment by benoitkugler** [comment]
En effet, j'ouvre la nouvelle "issue" #75
