### ISSUE TITLE
[server/expression] Délimiteur ensemble et espaces

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#161]
![image](https://user-images.githubusercontent.com/105806953/213664084-03a65c36-74ab-47f2-b18c-470f18a02cc7.png)

**Comment by Guigui7707** [comment]
ça fonctionne si je mets {s_1;b} ou {a;s_2} ou {a;b} (enfin pas mathématiquement mais isyro accepte)

**Comment by benoitkugler** [comment]
Il s'agit d'un problème d'espace :  isyro comprend s indice "2}" 
C'est en fait un défaut de conception, qui est lié au besoin de pouvoir aussi rentrer du code latex arbitraire (dans les listes à ordonner par exemple).

Pour corriger le problème, je propose donc : 

- de ne plus accepter `}` dans les indices de variable : cela rendra la syntaxe de la question `{s_1;s_2}` valide
- de remplacer la syntaxe `@_<code latex>` par `"<code latex>"` : les guillements sont utilisés en Python par exemple, et jamais en math, donc ça me semble le délimiteur naturel. Par exemple, `randChoice(@_\ge, @_\le) `sera ré-écrit en `randChoice("\ge", "\le")`

Qu'en penses-tu ?
