### ISSUE TITLE
[prof/trivial] Suivi de la question courante 

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#164]
Montrer la question du groupe, puis ajouter un bouton pour voir le détail (prévisu) (avec les paramètres instanciés).

**Comment by benoitkugler** [comment]
@Guigui7707  Questions restantes : sur l'appli de suivi, est-ce qu'on veut les mêmes fonctions que sur l'éditeur, c'est à dire : 

1. pouvoir valider/corriger la question ?
2. pouvoir afficher la bonne réponse ?

**Comment by Guigui7707** [comment]
Je pense que pas besoin de valider/corriger !
Pour afficher la bonne réponse vu le cas de configuration c'est pour corriger avec la classe donc à mon avis on peut s'en passer aussi ! Puisque le prof corrigera en live.
