### ISSUE TITLE
[eleve] Accès libre aux exercices

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#177]
Pouvoir refaire les exercices indépendamment de la notation et la date de cloture.

**Comment by benoitkugler** [comment]
Nouvelle activité (et nouvel page prof.) utilisant la même structure de feuille d'exercices.

**Comment by benoitkugler** [comment]
@Guigui7707 Peux-tu me confirmer que tu préfères une nouvelle activité (donc une nouvelle icône et un nouveau nom) sur l'appli élève ?
Sinon l'alternative serait d'avoir un bouton "Travail libre" (ou similaire) à l'intérieur de "Travail à la maison".
Je te repose la question car les deux activités sont quand même assez semblables, et que pour le Trivial, la distinction "libre/encadré" se fait à l'intérieur de l'activité.

**Comment by benoitkugler** [comment]
Autre question (cf message vocal) : peut-on simplifier et retirer le réglage Non noté (avec l'idée qu'une feuille non notée serait en accès libre) ?

**Comment by Guigui7707** [comment]
Pour la première question je ne sais pas... C'est vrai que "révisions" parait bien mais en fait si on peut homogénéiser c'est bien aussi je pense...

1. En page d'accueil "Triv'maths" (puis à l'intérieur il choisit accéder à une partie ou créer une partie) + "travail à la maison" comme c'est actuellement (peut-être ajouter le fait que ce soit noté style "devoirs (notés)" ou "travail à la maison (noté)") + "Révisions".
2. En page d'accueil "Triv'maths" (puis à l'intérieur il choisit accéder à une partie ou créer une partie) + "travail à la maison" (puis à l'intérieur il choisit entre "devoirs (notés)" ou "révisions")

En vrai le premier je l'aime car il est clair pour l'élève directement+il évite peut-être le mot "travail" qui est peut-être annoté négativement par les élèves, mais il ajoute une icône à la page d'accueil
En vrai le deuxième je l'aime car il permet de simplifier l'interface et de toute façon les élèves auront vite pigé qu'il faut cliqué que "travail à la maison" puis sur "devoirs (notés)"

Franchement, je te laisse trancher :)

**Comment by benoitkugler** [comment]
Je préfère alors la deuxième solution. Peut-être qu'on peut changer "Travail à la maison" ?
En "Pour m'entraîner" ? Ou "Exercices" ? Ou autre ?

**Comment by Guigui7707** [comment]
Ok parfait !
On peut laisser "Travail à la maison" ça me va ! Ou "Isy'taf" mais un peu kitch ^^
