### ISSUE TITLE
[prof] Questions de bases compte profs

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#179]
Je me dis que si des profs pas de maths accèdent à l'interface prof en se créant un compte, il faudrait qu'ils n'aient pas les questions de maths de notre base, du moins un menu déroulant permettant de sélectionner UNE matière à la fois et là ça affiche toutes les questions de notre base de la matière en question.

**Comment by benoitkugler** [comment]
Ah c'est très intéressant. Donc j'imagine qu'on rajoute une étiquette (speciale) pour la matière à chaque question.
Question : est-ce qu'on imagine un scénario où un même compte veut avoir plusieurs matières ?

**Comment by Guigui7707** [comment]
Du coup, il serait top de ne laisser la main aux profs que sur les questions de leur matière pour se prononcer sur les questions soumises par d'autres. (onglet "Discuter des publications en cours") Puisqu'ils ne sont experts que de la matière où ils ont passé le concours ;)
De notre côté bien sûr on garde la main pour la validation finale d'une question dans la base, idéalement on ne devrait les voir dans notre base une fois qu'au moins deux votes sont attribués à la question ET plus de 80% de "Oui" sur l'ensemble des votes (tant que la communauté isyro est petite).

**Comment by benoitkugler** [comment]
Tous les comptes math sauf perso Guillaume (Histoire)
