### ISSUE TITLE
Création d'une fonction spéciale

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#18]
Au même titre que isPrime et consorts, créer une fonction qui renvoie le max entre plusieurs valeurs, une autre pour le minimum

<img width="930" alt="isyro" src="https://user-images.githubusercontent.com/105806953/170789002-055bc34d-658f-4e4e-9b67-217004261968.PNG">

**Comment by benoitkugler** [comment]
Et ajouter la documentation
