### ISSUE TITLE
Visuel vecteur colonne

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#180]
Juste je ne sais pas s'il est possible de réduire l'épaisseur des parenthèses pour la présentation vecteur colonne sur un champ de réponse.

<img width="235" alt="isyro4" src="https://github.com/benoitkugler/maths-online/assets/105806953/5aed03db-b31c-4761-9afa-4cfa90f35e21">

**Comment by benoitkugler** [comment]
Oui sûrement !
(L'épaisseur vient du fait qu'il y a deux lignes, pour garder le ratio largeur hauteur, mais on doit pouvoir étirer le caractère ici.)
