### ISSUE TITLE
Affichage long détails

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#182]
Lorsqu'une question ne tourne pas sur l'interface prof (à cause d'une division par zéro par exemple), un message orange d'erreur s'affiche. On peut alors cliquer sur "Détails" afin de voir les valeurs simulées et ainsi comprendre d'où vient le bug. Seulement cet écran avec les variables et leurs valeurs affectées ne s'affiche que quelques secondes puis disparaît automatiquement. Il faudra qu'il reste indéfiniment jusqu'à ce que le prof le ferme ou clique à l'extérieur du cadre pour revenir au codage de la question.

**Comment by benoitkugler** [comment]
Arf oui en effet !
