### ISSUE TITLE
Lisibilité enseignant création nouvelle question

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#184]
Il faudrait un bouton très explicite et visible en premier dès qu'on clique sur "créer ou modifier une question" sur le site prof. Car pour le moment on accède à la liste des questions existantes et il faut rentrer dans une avant de voir un bouton "nouvelle question"

**Comment by benoitkugler** [comment]
On est d'accord que tu parles de la vue par niveau/chapitre, c'est ça ?

**Comment by Guigui7707** [comment]
Oui c'est ça, en effet depuis "liste" on voit "créer" mais il faudrait aussi qu'on voit "créer" directement puisqu'on tombe sur la présentation par chapitre en premier lieu.
