### ISSUE TITLE
Normes d'un repère

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#19]
Pauline s'est trompée en voyant le trait en gras à 5 carreaux elle a pensé que c'était l'unité et a divisé tous les bons résultats par 5
Il faudrait donc ajouter le point I et le point J sur les axes pour donner l'unité.
<img width="199" alt="isyro" src="https://user-images.githubusercontent.com/105806953/170834398-5d9be659-7fd5-4713-b8e0-57b90e5fc19f.PNG">

**Comment by benoitkugler** [comment]
Que penserais-tu de plutôt ajouter une légende en dessous des traits gras ? (-10,-5,5, 10,...)
Mes deux "objections" contre I et J sont que : 
- visuellement, j'ai l'impression que ça alourdi un peu plus et qu'il a un risque de confusion avec d'autres points
- a titre personnel, je n'insiste pas trop sur cette notation en classe (car je crois qu'il n'y en a qu'en maths qu'on l'utilise et qu'il s'agit selon moi surtout d'un souci de rigueur qui dépasse souvent le niveau que je vise)

**Comment by Guigui7707** [comment]
Oui c'est très bien ! Aucun problème c'est parfait !
