### ISSUE TITLE
Interface prof, conception d'une feuille d'exercice

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#193]
J'essaie de me projeter pour l'an prochain,
Et je pense qu'il serait judicieux que lorsqu'on ajoute une question dans une feuille d'exercice on puisse sélectionner la question complète (donc envoyer une des variantes de la question aléatoirement), voir même sélectionner en plus un items 1 étoile ou 2 étoile ou 3 étoiles (par défaut : ça envoie toutes les variantes si aucune case n'est cochée) pour que ça envoie une des variantes de la question affectée du nombre d'étoile sélectionnées.
Actuellement on doit cliquer sur une seule variante de la question, donc on doit cliquer sur toutes les variantes une à une si on veut toutes les mettre, et cela génère autant d'exercices.
Je sais pas si tu m'as suivi et si c'est envisageable.

**Comment by benoitkugler** [comment]
Il me semble qu'il y  a deux aspects ici : 

- pouvoir rapidement inclure une question et toutes ses variantes 
- avoir un choix _aléatoire_ pour l'élève

Le premier point se résout sans problème : inclure une question entière serait un raccourci pour inclure chacune des variantes (avec une option pour la difficulté).

Le deuxième point mérite plus de réflexion. Est-ce que ce n'est pas surprenant que deux élèves n'aient pas les mêmes questions ? Pour un élève donné, quand est-ce que l'aléa se produit ? Une seule fois quand il ouvre la feuille ? Après avoir réussi une question ?

Pourrais-tu décrire le scénario que tu as en tête _côté élève_ ?

Peut-être qu'une solution serait de permettre un certain aléa uniquement en mode entrainement : on pourrait imaginer par exemple que par défaut, on propose aléatoirement une question au lancement de l'activité. Mais il me semble qu'il faudrait quand même que l'élève puisse choisir, si besoin, la question qu'il souhaite travailler.

**Comment by Guigui7707** [comment]
Hum, merci beaucoup pour tes réflexions et questions qui éclairent en effet je n'avais pas pensé à tout.
Du point de vue évaluatif il est évident qu'on ne peut pas rendre un travail plus difficile pour un élève qu'un autre, même si les tentatives sont "illimités" jusqu'à réussite de l'élève.
Néanmoins je prends un exemple : 

- si le prof code une question avec une seule variante où il faut donner la forme canonique à partir de la développée, mais que une fois sur deux ça envoie en "alpha" négatif eh bien dans la même question la difficulté est aléatoire. (-alpha donne --2 par ex donc +2)

- si le prof code une question avec deux variantes une avec un alpha positif (facile) et une avec un alpha négatif (moyenne) alors oui ici envoyer aléatoirement donnera comme dans le premier cas une difficulté aléatoire.

Dans l'idéal il faudrait coder systématiquement comme le cas n°2, mais il est inévitable qu'il y ait des trous dans la raquette et que je fasse des oublis, ou que je n'ai pas le temps de distinguer tous les cas en permanence (travail très intéressant néanmoins, que j'aime beaucoup). Encore plus pour tous les profs qui créeront leurs propres questions. Ils risquent d'aller à l'essentiel (=1 question qui tourne) sans distinguer les cas (par manque de temps ou même d'envie).

A partir de là je crois qu'on peut dire qu'un exercice restera "inégal" pour deux élèves donnés, même s'il est noté.
Autrement dit ça ne me gêne pas personnellement que des élèves tombent sur des cas "plus difficiles", tant qu'ils peuvent recommencer jusqu'à réussite soit ils auront un cas plus facile au coup d'après, soit ils finiront par devoir réussir ce cas plus compliqué.
D'ailleurs, l'ajout d'étoiles par exemple pour une question sélectionnée permet même de limiter les différences de niveau de questions (comme on peut ajouter à chaque variante un nombre d'étoile : MERCI au passage !).
En fait, conserver le fait de sélectionner une question + sa variante précise reste un bon choix. Mais tu es l'expert pour la mise en œuvre et si cela devient fouillis dis-le moi bien sûr, je peux faire fausse route !

**Comment by Guigui7707** [comment]
Bref, pour un scénario élève je verrais : 

Le prof met des devoirs à la maison : question n°73 répété 3 fois, variantes 1 étoile (soit la 73a et la 73b par exemple).
Aléatoirement il tombe sur 73b 73b et 73a. Il réussit la première et échoue aux deux autres. En retentant une deuxième fois celle-ci, l'ordinateur envoie aléatoirement 73a et 73a pour les deux dernières qu'il retente. Il les traite comme ça.

Mais pour le côté entraînement libre, en effet ce serait top que l'élève puisse voir les variantes et choisir de s'entraîner sur toutes. A ce moment il faudrait que le prof puisse continuer de mettre une variante d'une question en la sélectionnant directement comme c'est le cas actuellement.

Franchement c'est une friche ce sont des choix pédagogiques très intéressants mais je n'ai pas encore de recul là-dessus je t'avoue... Voir 6 variantes sur une même questions en révisant son contrôle peut-être décourageant (masse pour un seul thème) et peu utile (les variantes sont sensiblement proches) pour l'élève. Aussi, pour le tableau de signe avec Delta c'est, il me semble, à la fois nécessaire que l'élève rencontre les 6 cas (signe de a, signe de delta) ET ne sélectionne pas une question qui tombe toujours sur un tableau de signe identique (un moins au milieu et basta). S'il s'en rend compte il fera un théorème "la n°3 c'est toujours moins au milieu !"

**Comment by benoitkugler** [comment]
Autre question : est-ce tu envisages le même changement pour les exercices ? Ou pas ?

**Comment by Guigui7707** [comment]
Pour les exercices je n'en ai que peu codé, j'ai l'impression que je ne ferais qu'une variante par exercice mais peut-être que je me trompe... Car c'est suffisamment long de faire 6-7 questions d'affilées déjà ! Donc je me prendrais pas trop la tête pour les expressions avec des moins ou que des plus, ce sera tout d'un coup je pense. Car l'outil est focalisé sur la réflexion plus que les technicités de calculs.
