### ISSUE TITLE
Problèmes d'affichage ?

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#195]
Je n'arrive pas à comprendre, on m'annonce en bas 17 questions avec les critères sélectionnées, mais je n'ai que deux pages de 6 questions soit 12 au lieu de 17... Y a-t-il quelque chose que j'ai raté ?

![image](https://github.com/benoitkugler/maths-online/assets/105806953/266fbaf4-24e5-46d7-9ff7-37fba937a4a0)

**Comment by benoitkugler** [comment]
Arf, ça ressemble à une erreur de division euclidienne ça : 17 = 6 * 2 + 5 => 3 pages, pas 2 !
Désolé..

**Comment by Guigui7707** [comment]
Ah ah pas de soucis
