### ISSUE TITLE
Interface prof, présentation des trivials proposés

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#196]
Je n'ai pas trop d'idée mais la page de lancement des triv'maths est pas hyper évidente à lire, surtout depuis le compte prof.
Bon en même temps faut que je fasse du tri dans les triv'math ^^
Mais pouvoir estampillé le triv'maths d'une classe et d'un chapitre déjà utilisé dans les questions serait bien pour pouvoir trier comme on le fait actuellement pour les questions + peut-être une sélection "mes triv'maths"/"les triv'maths proposés par isyro" OU en proposer deux par lignes (donc deux colonnes) avec peut-être un déroulant qui indique le nombre de question par couleurs.
M'enfin dis-moi ce que tu en penses !

**Comment by benoitkugler** [comment]
Oui tu as raison.. OK pour ajouter un classement, et les deux colonnes c'est une bonne idée aussi, je vais voir !

**Comment by Guigui7707** [comment]
En fait ce qui est fait pour l'affichage des questions (par classe puis par chapitres) est TRÈS clair et facile d'utilisation !
En ajoutant ce qui est propre au triv'maths (le nombre de questions par couleurs, la modification, le lancement) ça devrait être parfait
