### ISSUE TITLE
[serveur/questions] Aléa tableaux de signes

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#200]
Sur l''exercice qui demande le tableau de signe d'un trinôme,
Si Delta >0 ça propose toujours à l'élève "2-3 ou 4" signes.
Si Delta = 0 ça propose toujours à l'élève "1-2 ou 3" signes.
Si Delta < 0 ça propose toujours à l'élève "1 ou 2" signes.

Je me dis qu'un élève qui tourne dessus va capter le théorème et choisir sans forcément réfléchir.
Je ne sais plus comment ça envoie aléatoirement le nombre de signes distincts dans le tableau.
Le top serait d'envoyer : 1-2-3 / 2-3-4 pour delta positif
pour delta nul : 1-2-3 / 2-3-4
pour delta négatif : 1-2-3 / 2-3-4
Mais je ne sais pas si c'est possible

**Comment by Guigui7707** [comment]
heu pour delta négatif impossible d'envoyer 2-3-4 mince ^^ donc juste 1-2-3 ou 1-2 peut-être

**Comment by benoitkugler** [comment]
Oui c'est possible. En fait les propositions dépendent juste du nombre de signes de la réponse, donc on peut tout à fait coder la règle que tu proposes :
3 signes =>  1-2-3  _ou_ 2-3-4
1 signe => 1-2-3 _ou_ 2-3-4

**Comment by Guigui7707** [comment]
Je pense que le max dans un tableau de signes sera 3 ou 4 signes je n'ai jamais vu plus.
Donc pour 3 signes nikel

Pour 1 signe attention 2-3-4 ne permet plus de sélectionner le 1 justement !

**Comment by benoitkugler** [comment]
> Pour 1 signe attention 2-3-4 ne permet plus de sélectionner le 1 justement !

Oups oui, j'ai corrigé mon commentaire.
