### ISSUE TITLE
[eleve] citation sur travail à la maison

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#202]
Je trouve l'idée top de mettre les citations aussi sur l'interface "Travail à la maison" ! Actuellement elles sont sur les corrections mais en codant souvent je dépasse de l'affichage et il faut descendre vers le bas. La citation étant affichée en bas elle perturbe car on croit que la correction est finie alors que non.
Peut-être la mettre soit juste au-dessus ou juste au-dessous de la du bouton "validation" de la question,
Ou tout en bas de la correction détaillée, pas de l'écran.

Je ne sais pas à quel moment c'est le mieux où l'élève sera plus disposée à la lire.. (certains ne consulteront pas les corrections je pense par exemple donc peut-être à la question, mais en même temps ils seront peut-être pressés de valider j'en sais rien)

**Comment by benoitkugler** [comment]
Bien vu (je pense que je n'ai pas testé l'affichage avec une correction "longue")

> Ou tout en bas de la correction détaillée, pas de l'écran.

Cela me semble le plus simple et le plus clair.

> Je ne sais pas à quel moment c'est le mieux où l'élève sera plus disposée à la lire.. (certains ne consulteront pas les corrections je pense par exemple donc peut-être à la question, mais en même temps ils seront peut-être pressés de valider j'en sais rien)

D'accord, on pourra affiner et y revenir avec l'expérience.
