### ISSUE TITLE
Tableau de variations pré-complétés

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#203]
Les tableaux de variations sont pré-complétés par ( )/( ) pour comme convenu préparer la notation fraction quand il y a plusieurs termes au numérateur ou dénominateur.
Seulement en pratiquant avec Pauline ce soir on s'aperçoit que c'est long de compléter soit en enlevant tout de la case soit en cliquant au bon endroit. Et dès qu'il y a des entiers il faut enlever. Surtout avec 3 calculs d'images etc.
Je pense qu'il serait préférable finalement de laisser les champs vides et l'élève les remplit.

**Comment by benoitkugler** [comment]
Bien d'accord, ça surcharge l'affichage en plus.
Je pense que c'est plutôt un bug, je ne pensais pas le mettre sur les tableaux..
J'avais ouvert #190 pour ça ;)
