### ISSUE TITLE
[eleve] Affichage timer

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#204]
Certains élèves s'étaient "plains" de ne pas voir la barre du timer quand ils répondent à une question où le pavé numérique doit s'afficher (il cache alors cet élément). Je ne sais pas si c'est possible de le maintenir au-dessus du pavé mais en même temps l'idée c'est de ne pas cacher la question ou du moins certains éléments de la question ! Alors je te laisse trancher ce n'est pas forcément vitale même si ça les stresse (bon en voyant le temps défilé ça les stressera peut-être encore plus ^^)

**Comment by benoitkugler** [comment]
Hum .. c'est vrai que l'effet visuel n'est pas top. Est-ce mettre la barre tout en haut (juste en dessous du titre) irait ?

**Comment by Guigui7707** [comment]
Oui très bonne idée !!
