### ISSUE TITLE
[eleve/trivial] Affichage final

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#205]
Dans une partie à 2 joueurs (et peut-être plus), le dernier joueur qui appuie sur "Suivant" voit le tableau final avec les vainqueurs ; mais l'autre à une citation affichée au milieu (et en bas : en attende du JoueurXXX) qui cache les vainqueurs notamment. Surtout, je n'avais pas accès au décrassage comme si l'écran avait bugué.

**Comment by Guigui7707** [comment]
Je parle du triv'maths

**Comment by benoitkugler** [comment]
Ça ressemble à un bug, car un évènement "fin de partie" est envoyé aux deux joueurs normalement..
Je vais voir si j'arrive à le reproduire
