### ISSUE TITLE
Détails (fluidité prof)

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#21]
Pouvoir créer son propre trivial en tapant les premières lettres quand on ajoute une étiquette dans une couleur de camembert (et pas juste descendre avec la barre pour cliquer sur l'étiquette voulue).

**Comment by Guigui7707** [comment]
+ quand on cherche une question dans la base et qu'on écris var puis qu'on clique sur l'étiquette variations l'étiquette s'ajoute mais le "var" reste dans la barre de recherche. Il faut alors effacer le var pour ajouter une autre étiquette (on peut s'arranger les choses en cliquant hors de la barre de recherche puis de nouveau dedans, là ça supprime le "var" ; mais ce n'est pas le cas sur la création d'un trivial avec les étiquettes où là on s'emmêle plus facilement les pinceaux en risquant de cliquer hors de la fenêtre sans s'enregistrer)

**Comment by Guigui7707** [comment]
(ajout)

**Comment by Guigui7707** [comment]
Toujours dans le même style, quand on cherche une question avec un mot-clés ou une étiquette, qu'on la sélectionne puis qu'on met retour depuis la question, ce serait top de conserver la recherche précédente dans les barres de recherches (car souvent je switche entre les mêmes questions de difficultés ou cas différents, ce qui fait refaire une recherche systématiquement).
<img width="706" alt="isyro" src="https://user-images.githubusercontent.com/105806953/172104937-659c7ac4-ec45-477b-8de0-59d032c8ed97.PNG">
<img width="714" alt="isyro2" src="https://user-images.githubusercontent.com/105806953/172104944-95046dcc-b7a9-42dc-8484-a73fb21990a2.PNG">
<img width="706" alt="isyro3" src="https://user-images.githubusercontent.com/105806953/172104961-cfcbbc15-569e-4111-89f6-870727054bbf.PNG">

**Comment by Guigui7707** [comment]
Bon après ça ne concerne peut-être que moi puisque je code beaucoup... donc pas forcément judicieux ce dernier point

**Comment by benoitkugler** [comment]
Ca me semble un bon changement en général (plus cohérent)

**Comment by benoitkugler** [comment]
Une partie du problème est résolu, #41 reste ouvert pour le reste.
