### ISSUE TITLE
[prof] Classes

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#213]
Je me demande s'il ne serait pas judicieux de pouvoir spécifié plus précisément que "première" et "terminale" : il y a terminale STMG, première STMG, première spé, terminale spé.
Certains exos ne seraient que dans une seule classe mais d'autres devraient pouvoir être sélectionnés chez "première spé" mais aussi chez "première STMG".

Donne-moi ton avis!
Ça pourrait être une étiquette sous le niveau général "première"..

**Comment by benoitkugler** [comment]
Oui tu as raison, il y a une nette différence entre première spé et première STMG..
Pour autant, je pense qu'il faut éviter d'être trop précis, pour éviter ensuite le dilemme "dans quelle case je met ma question".. 
Donc peut-être introduire deux étiquettes première spé/ première techno (et pareil pour la terminale) ?

**Comment by benoitkugler** [comment]
Hum, j'ai lu un peu trop vite : les ressources concernant deux classes (spé et techno) seraient problématiques avec ma proposition.
Si je comprends bien il faudrait en gros 3 catégories : première partagée, première spé, première techno. Tu confirmes ? Si c'est bien ça, le mieux serait en effet d'avoir des sous étiquettes (optionnelles), comme tu l'as proposé.

**Comment by Guigui7707** [comment]
Oui première puis possibilité (ou obligation ?) de flécher avec une étiquette première spé ou première techno (mais là il y a STMG, STI2D et ST2S qui ont des programmes différents encore..)
Idem avec les terminales

**Comment by Guigui7707** [comment]
Enfin c'est un peu flou à vrai dire, si on met 3 catégories ça va classifier bizarre pour les chapitres...
Il faudrait première puis les sous-étiquettes des filières, ou la possibilité de glisser une question à la fois dans première spé et dans première STMG si on ne fait pas d'étiquettes principales première

**Comment by Guigui7707** [comment]
Par exemple dériver un polynôme simple irait dans les deux mais dériver un polynôme de degré 5 que chez les premières spé.
Alors aller chercher la question simple dans "première" et la compliquée dans "première spé" paraît complexe sachant que les deux doivent être au même endroit (pour les premières spé)

Pour le moment tu peux laisser comme ça sinon, on en reparle ^^ l'an prochain j'ai une terminale et une première donc le problème ne se pose pas

**Comment by benoitkugler** [comment]
Prévoir possibilité plusieurs sous étiquettes (liste)
N'influe pas sur les chapitres
Nouveau menu déroulant
Migration base admin : première -> première spé
