### ISSUE TITLE
Visuel prof triv'maths

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#217]
Pourquoi ne pas faire apparaître dès le début la poubelle et le crayon, comme c'est déjà le cas pour le partage public et le partage accès libre à une classe ? (tu as peux-être des raisons que j'ignore)

![image](https://github.com/benoitkugler/maths-online/assets/105806953/c021476c-2ba4-46da-8cd4-56049cf9f701)

**Comment by benoitkugler** [comment]
Je trouve que ça alourdit d'avoir trop de boutons, mais bon c'est très subjectif..
Idéalement les fonctions moins utilisées sont dans le menu déroulant.

Tu trouves que ça manque d'ergonomie ?

**Comment by Guigui7707** [comment]
Non c'est tout bon laisse comme ça ! Je me demandais juste!

**Comment by benoitkugler** [comment]
Je trouve que trop de boutons alourdissent le visuel, mais c'est subjectif.
Idéalement, les fonctions les moins utilisées sont dans le menu déroulant.

Tu trouves qu'il y a un manque d'ergonomie ?

**Comment by benoitkugler** [comment]
OK, on ré ouvre le fil si à l'usage c'est bof..
