### ISSUE TITLE
[prof] Menu à dérouler

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#218]
(idée !! Qu'en penses-tu ?)
J'aime bien le menu déroulé que tu utilise dans "Travail à la maison" et "Favoris" qui consiste à avoir juste le bandeau des niveaux et en cliquant dessus ça déroule les feuilles favorites par niveau de classe.
Est-ce que la même chose pour les "Questions", les "Exercices" et les "Triv'maths" serait judicieux ? Pour le moment pas de soucis puisqu'il y a "peu" d'exercices et de niveau de classe, mais en étoffant + en démultipliant peut-être les classes à l'avenir (première techno, term techno) ça va bien allonger la barre pour descendre dans la page.
Le hic c'est que ça rajoute un clic, mais ce serait en remplacement de la de la molette pour descendre la page.
Mais actuellement ça donne directement un bon visuel je trouve.

**Comment by benoitkugler** [comment]
Pourquoi pas ! 

Comme tu l'as dit, on peut attendre que la base s'étoffe avant d'essayer.
