### ISSUE TITLE
Réponse type vecteur directeur d'une droite

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#22]
Comment faire pour valider plusieurs réponses possibles qui sont toutes justes?
Exemple de citer deux vecteurs colinéarité d'une figure ou de lire un vecteur directeur sur une droite.
Idée : créer un type de réponse qui permet de calculer le rapport abscissevecteur/ordonnéevecteur proposé par l'élève dans deux champs de réponses un abscisse et un pour ordonnée (exception faite aux droites verticales et vecteurs de direction verticale)

**Comment by benoitkugler** [comment]
Comparer en terme de colinéarité
