### ISSUE TITLE
Arbres pondérés, modèles proposés

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#220]
J'aurais besoin d'afficher un arbre "champ de réponse" (mais aussi "énoncés" plus tard) qui n'a pas la même structure en terme de probabilités. Exemple : 0,2 et 0,8 au départ (ça c'est OK) mais 0,3 et 0,7 à partir du 0,2 PUIS 0,4 et 0,6 à partir du 0,8. Sachant que les événements en première ligne sont A et B (OK) mais en deuxième "colonne" (en deuxième ligne pour isyro) c'est M et m PUIS M et m de nouveau !
Je peux rajouter des "prime" comme M' et m' pour dissocier mais un problème subsiste : comme l'élève choisit les événements ET les probas sur les branches il peut très bien partir "à droite" pour A alors que le prof l'a construit et corrigé en "à gauche" pour A.
Enfin, je ne peux pas vraiment vérifié car : je ne peux pas voir ce qu'il se passe à droite sur l'arbre car je suis sur PC (impossible d'aller à droite en touchant l'écran avec mon pouce) ET quand je complète les champs de réponses automatiquement le bouton "Valider" ne s'allume pas pour pouvoir valider c'est impossible.

**Comment by benoitkugler** [comment]
> quand je complète les champs de réponses automatiquement le bouton "Valider" ne s'allume pas pour pouvoir valider c'est impossible.

Hum, je n'ai pas ce problème de mon côté. On parle bien du bouton "Afficher la réponse" en haut à droite, puis du bouton "Valider" à  la fin de la question ?
