### ISSUE TITLE
[eleve] Affichage arbre

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#221]
C'est juste une question car je ne connais pas les tenants et aboutissants : 
Sais-tu pourquoi nous avions choisi de présenter les arbres de manière "colonnes" ?
Simplement parce qu'au bac ils sont toujours présentés de manière "ligne". Ils sont aussi toujours à deux étages (au max : 2 branches à la première colonne puis 3 branches issues à la deuxième colonne).
Dans le supérieur ce genre d'arbres est-il utilisé ? Je suppose que la loi binomiale remplace cet outil.

**Comment by Guigui7707** [comment]
Voir dans tous les cas **s'il est possible** de réduire "l'étalage" de l'arbre qui est assez volumineux en affichage sur l'écran élève (et sur l'écran prof en codant la question d'autant qu'on ne peut pas décaler avec la souris pour le voir en entier ; d'ailleurs en passant en arbre "colonne" et pas "ligne" comme c'est actuellement cela poserait problème pour vérifier le travail de codage puisque là je peux voir chaque "ligne")

**Comment by benoitkugler** [comment]
> Sais-tu pourquoi nous avions choisi de présenter les arbres de manière "colonnes" ?

C'était essentiellement un choix arbitraire.
En renversant l'ordre, on aurait sûrement besoin de Scroll à la fois horizontalement et verticalement, ce que je trouve un peu moins ergonomique (sauf s'il n'y a que deux niveaux avec des évènements d'une seule lettre).



> Dans le supérieur ce genre d'arbres est-il utilisé ? Je suppose que la loi binomiale remplace cet outil.

En effet, on utilise peu les arbres, la rédaction idéale (en CPGE en tout cas) utilisant plutôt des probas conditionnelles 

> Je pense notamment à l'encadré des événements qui sont larges alors que ce seront uniquement des lettres.

Intéressant. J'ai mis une largeur minimal pour que les probas ne se marchent pas dessus, mais on peut peut-être affiner malgré tout. Ou alors changer de forme tiens, en utilisant un escalier au lieu d'une flèche droite

**Comment by Guigui7707** [comment]
Quelques stats : dans les sujets bacs 2023, 75% des arbres demandés sont à deux niveaux. (vus sur APMEP, 9 sujets sur 12)

Ok !

Je pense que garder les largeurs comme ça me convient du coup, les escaliers les élèves vont les reproduire sur leurs copies ^^ Cette année sur Wims les arbres sont en étages comme actuellement sur isyro, et au DS de proba j'ai vu plusieurs de mes secondes me les prendre en étages (en cours/en classe on faisait comme au bac, donc de la gauche vers la droite). Alors si au bac ils les font en étages et avec des escaliers c'est pas faux mais ça va surprendre le correcteur, ça ne sera pas à leur avantage =D
