### ISSUE TITLE
[questions] Probabilités sur arbres

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#223]
Je ne sais pas dans quelle mesure c'est possible, mais ça pourrait être top d'afficher sur une branche de l'arbre une probabilité qui n'est pas décimal comme 1/3.

**Comment by Guigui7707** [comment]
Aussi, est-ce possible d'afficher "x" sur une branche, étant une probabilité inconnue à déterminer par l'élève ?

**Comment by benoitkugler** [comment]
Pour une raison technique, je ne sais pas comment afficher correctement un code LaTeX sur les branches. 
En revanche, une solution intermédiaire est de pouvoir afficher une expression sous forme de texte (style calculette). Par exemple, "x" et "1/3" serait possible.
