### ISSUE TITLE
[all/questions] Nouveau bloc

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#225]
Il faudrait construire un bloc réponse où l'élève construit la représentation graphique d'une suite ! Je suppose qu'une fois que tu as fais celui pour les fonctions ce doit être un cas simplifié.
Il faudrait aussi un bloc énoncé où on puisse afficher une suite graphiquement pour faire conjecturer l'élève sur le sens de variation ou lire graphiquement les termes de la suite.

**Comment by benoitkugler** [comment]
> Il faudrait construire un bloc réponse où l'élève construit la représentation graphique d'une suite ! Je suppose qu'une fois que tu as fais celui pour les fonctions ce doit être un cas simplifié.

Bien vu ! Que penses tu de regrouper cette fonction dans le bloc existant (construction de fonctions) ? (Avec une option pour pouvoir différencier suites et fonctions)

> Il faudrait aussi un bloc énoncé où on puisse afficher une suite graphiquement pour faire conjecturer l'élève sur le sens de variation ou lire graphiquement les termes de la suite.

Bien vu encore ;) 
Là aussi, il me semble qu'on pourrait ajouter cette fonction dans le moule des graphes : ce serait une sous catégorie de plus. Qu'en penses tu ?

**Comment by Guigui7707** [comment]
Oui très bien d'ajouter au bloc déjà existant pour les fonctions! C'est mieux même :)
