### ISSUE TITLE
choiceFrom

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#226]
Cela fait plusieurs fois que je cherche une solution en vain : comment envoyer "aléatoirement" avec choiceFrom (ou autre mais j'aimerais maîtriser cet aléa) un "-" ou un "+" ?
Par exemple ici, c'est pour envoyer une limite corrigée qui fait soit -infini soit +infini.

**Comment by Guigui7707** [comment]
Même question pour envoyer aléatoirement un espace insécable (quand la réponse est +infini, -infini ou zéro dans une réponse corrigée j'aimerais envoyer aléatoirement -/+/espace insécable puis infini/infini/zéro)

**Comment by benoitkugler** [comment]
> Cela fait plusieurs fois que je cherche une solution en vain : comment envoyer "aléatoirement" avec choiceFrom (ou autre mais j'aimerais maîtriser cet aléa) un "-" ou un "+" ? Par exemple ici, c'est pour envoyer une limite corrigée qui fait soit -infini soit +infini.

En fait, il faut intégrer le signe dans une expression mathématiques bien formée. Donc par exemple, choiceFrom(inf, -inf) ou alors, choiceFrom(1, -1) (puis multiplier)

> Même question pour envoyer aléatoirement un espace insécable (quand la réponse est +infini, -infini ou zéro dans une réponse corrigée j'aimerais envoyer aléatoirement -/+/espace insécable puis infini/infini/zéro)

Hum, ici il y a deux aspects il me semble.
Si c'est une question uniquement de présentation d'une **expression valide**, isyro devrait automatiquement ajuster les espaces. Si ce n'est pas encore le cas, on devrait travailler dessus pour corriger ça.
En revanche, si tu veux insérer des termes qui ne suivent pas la syntaxe mathématique usuelle, il faut utiliser les guillemets `"` pour insérer du texte libre.
D'après ce que j'ai compris, on est dans le cas 1. Pourrais tu confirmer, avec peut être une capture de ce qui ne s'affiche pas correctement ?

**Comment by Guigui7707** [comment]
Merciiiii pour le + ou - infini !!! C'est parfait. Je devrais plus penser à te consulter en effet pour ce genre de choses avant de chercher à créer une nouveauté, je ne pense pas à tout en effet... !

Pour la deuxième remarque je te la soumet donc,
Je voulais faire un exercice qui envoie aléatoirement "AU MOINS une fois face" ou "EXACTEMENT une fois face" (pour contourner je peux mettre MINIMUM et EXACTEMENT mais ce n'est pas la terminologie la plus répandue. Pour contourner je peux tout à fait faire 2 variantes plutôt qu'une. C'est juste quand j'essaie d'optimiser que je suis confronté à ce problème, qui d'ailleurs peut me reposer problème dans la correction détaillée où souvent il vaut mieux multiplier les variantes car elles n'utilisent pas forcément le même nombre de ligne de calculs dans la correction ou la même tournure de phrase.

**Comment by benoitkugler** [comment]
> Je voulais faire un exercice qui envoie aléatoirement "AU MOINS une fois face" ou "EXACTEMENT une fois face"

Je ne crois pas avoir saisi le problème. Est-ce qu'il y a quelque chose de bloquant avec
choiceFrom("Au moins", "exactement")

**Comment by Guigui7707** [comment]
Autre demande du même style, je ne trouve pas comment taper avec les & et les $ une expression dans ce cas qui permette de basculer directement le +- en en -. Ainsi j'aimerais envoyer "aléatoirement" un + ou un - avec choiceFrom mais cela n'est pas reconnu (là sur la photo c'est avec randChoice mais le problème est identique. As-tu une idée ?

![image](https://github.com/benoitkugler/maths-online/assets/105806953/7e1aafe5-828c-4217-95ed-160e6fe600d5)

**Comment by benoitkugler** [comment]
Si tu veux uniquement le symbole du signe, tu peux utiliser les guillemets :
choiceFrom ("+", "-")

**Comment by Guigui7707** [comment]
Ah ok, c'est ce que tu expliquais avec les guillemets plus haut, je viens de capter. Merci !! C'est parfait
