### ISSUE TITLE
[eleve] aléa citations

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#227]
Je propose de faire de même pour les citations : sur une même partie de Triv'maths ou sur une même séance d'exercices faire en sorte que les citations pour l'élève ne soient pas répétées avant d'avoir fait une boucle complète

**Comment by benoitkugler** [comment]
OK, je pense que ce serait global sur l'appli, et réinitialisé à chaque lancement, si ça te va.
