### ISSUE TITLE
[prof] Liaison compte admin/compte prof pour Feuilles d'exercices favorites

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#230]
Lorsque je créé une feuille d'exercices sur le compte admin que je classe "favoris", elle n'apparaît pas sur mon compte perso "favoris".
Penses-tu qu'il serait bon de partager aussi ceci aux comptes profs ? Comme c'est déjà classé par classe actuellement ça permettrait d'avoir directement une séance qui regroupe tous les exercices d'un même chapitre par exemple sur une feuille en accès libre ou évaluée.
Bien sûr la créé soit-même va très vite car il existe une vingtaine de questions par chapitre tout en plus ; seulement réfléchir à l'ordre pour classer les exercices au sein de cette feuille du plan basique au plus complexe ET/OU du plus fondamental au "moins utile" peut ici être plus complexe (il faut naviguer d'une page à l'autre, etc).

**Comment by benoitkugler** [comment]
> Lorsque je créé une feuille d'exercices sur le compte admin que je classe "favoris", elle n'apparaît pas sur mon compte perso "favoris". Penses-tu qu'il serait bon de partager aussi ceci aux comptes profs ? Comme c'est déjà classé par classe actuellement ça permettrait d'avoir directement une séance qui regroupe tous les exercices d'un même chapitre par exemple sur une feuille en accès libre ou évaluée. Bien sûr la créé soit-même va très vite car il existe une vingtaine de questions par chapitre tout en plus ; seulement réfléchir à l'ordre pour classer les exercices au sein de cette feuille du plan basique au plus complexe ET/OU du plus fondamental au "moins utile" peut ici être plus complexe (il faut naviguer d'une page à l'autre, etc).

Oui ça semble une suite cohérente, qui est techniquement possible depuis la refonte de cette page.
J'imagine qu'on ajoute aussi la fonction de publication (perso -> admin) ?

**Comment by Guigui7707** [comment]
Oui c'est une bonne idée !
