### ISSUE TITLE
[questions] Graphique simultané bloc énoncé et bloc réponse

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#231]
J'essaie de coder un exercice où le graphique d'une fonction est affiché et l'élève doit par-dessus construire la tangente à la courbe en un point connaissant le nombre dérivé de la fonction en cette abscisse.
Penses-tu qu'il soit possible de grouper un graphique déjà affiché par le prof avec ce même graphique où l'élève doit construire la tangente ?

**Comment by benoitkugler** [comment]
Oui au fond ça semble possible : tous les champs de réponses (de type graphique) aurait un nouveau champ (optionnel) pour préciser une figure (avec exactement le même format que le bloc Figure actuel)

**Comment by benoitkugler** [comment]
Regrouper les blocs de création géométrique et ajouter un arrière plan (rien/figure/fonction)
