### ISSUE TITLE
[exercices] Idée étoiles

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#232]
Je me demandais si c'était une bonne idée :
(déjà, cela concerne la partie "autonomie" lorsque l'élève travaille seul pour réviser le chapitre)
Plutôt que seul le prof choisisse à l'avance la variante de la question avec tant de nombre d'étoiles de difficulté, que l'élève puisse (lorsque le prof sélectionne "inclure aléatoirement") partir sur le niveau 1 étoile (aléa si plusieurs variante à une étoile dans la question) automatiquement puis se voir proposer un bouton "m'entraîner sur un niveau 2 étoiles" (un truc du genre) lorsqu'il a réussi la question niveau 1 étoile.
(cela ne concerne donc pas les "devoirs à la maison" puisqu'en principe on ne cliquera pas sur "inclure aléatoirement" afin de respecter l'équité de la difficulté envers tous les élèves sur un travail noté)

Je ne sais pas ce que tu en penses ?
Une alternative à cela, très bien aussi, c'est simplement de dupliquer une séquence "favoris" qui fait réviser un chapitre à l'élève en autonomie et d'utiliser ton merveilleux bouton qui permet de sélectionner une étoile, deux étoiles, etc.

**Comment by benoitkugler** [comment]
C'est clairement une idée intéressante ! 
En revanche, elle me parait un peu trop complexe à mettre en oeuvre dans l'activité actuelle. 
Une simplification de ta proposition qui serait assez facile à mettre en oeuvre serait de : 

- générer (comme actuellement) une fois pour toutes les questions et de les proposer toutes d'un coup 
- mais de les générer (et de les présenter à l'élève) par ordre de difficulté. Exemple :

**Comment by benoitkugler** [comment]
Afficher la difficulté des questions
