### ISSUE TITLE
[trivial] Couleurs plateaux

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#236]
Adapter les couleurs pour les rendre plus accessibles 
Modifier la valeur max du dé  : à décider

**Comment by Guigui7707** [comment]
Bon mon fichier n'était pas très pratique à modifier ^^
Voici le plateau, seules 3 cases donnent une seule possibilités de couleurs, et c'est à chaque fois en faisant un 6.
Le plateau ne fait pas la part belle aux 6 puisqu'on retombe de part et d'autres sur les deux mêmes cases.
Donc si on veut on peut mettre un dé à 5 faces pour éviter ces 3 cas, sinon le 6 me va bien personnellement.

[T-Plateau.pdf](https://github.com/benoitkugler/maths-online/files/12318856/T-Plateau.pdf)

**Comment by benoitkugler** [comment]
Merci beaucoup ! Je n'ai pas d'avis fort sur la valeur max. du dé, donc mettons un 6 :)
