### ISSUE TITLE
[server] Question perso

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#244]
À quoi correspond le "non classé" tout en haut? Je n'ai pas trouvé où changer ce nom en créant ma feuille d'exercices. Et ça m'intéresse justement ;)

![Screenshot_2023-08-16-11-10-01-902_com.maths.isyro.jpg](https://github.com/benoitkugler/maths-online/assets/105806953/590a100e-aa72-4144-856a-5a8fe9f295c8)

**Comment by benoitkugler** [comment]
Hum, normalement ce sont les fiches sans étiquette de chapitre. C'est peut-être un bug, je vais vérifier (on avait un problème similaire la dernière fois, manifestement je n'ai pas ouvert de fil pour le traiter).
