### ISSUE TITLE
[eleve] Correction écran élève

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#245]
(c'est génial l'outil corrigé pour l'élève !!)
Le message "corrigé" peut-il rester à l'écran indéfiniment jusqu'à ce que l'élève choisisse "essayer à nouveau" ou "corrigé" ? Car il disparaît après 3-4 secondes et n'est plus accessible à moins de relancer une nouvelle question.

**Comment by benoitkugler** [comment]
Ah oui bien vu. Je pense que ce comportement fais sens quand il n'y a pas de correction lié à la question, mais en effet je n'y ai pas repensé quand on a ajouté les corrections.
