### ISSUE TITLE
[eleve] Horaire de fin

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#248]
Pour un devoir noté à rendre jeudi 7 septembre à 10h, un de mes téléphones m'affiche qu'il est à rendre avant 8h (pour ma première spé).
Idem pour un autre devoir noté du jeudi à 9h, un autre téléphone affiche 8h max (pour mes tstmg).
Je pense que cela vient du réglage de l'heure des téléphones ? Ou un décalage isyro câblé sur un autre fuseau horaire ?

**Comment by benoitkugler** [comment]
Argh, je me fais toujours avoir ! C'est une histoire de fuseau horaire en effet, il faut que j'affiche l'heure locale sur le téléphone élève.
Je corrige au plus vite et je publie une mise à jour (1.6.2)

**Comment by benoitkugler** [comment]
Les versions sont en "review" sur l'app store et le play store.

**Comment by benoitkugler** [comment]
La mise à jour est disponible sur les deux stores.
