### ISSUE TITLE
[prof/homework] Affichage notes

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#249]
PAS URGENT

Lorsque l'on veut afficher les notes, pré-sélectionner les feuilles qui sont notées OU qui ont été notés me paraît top (pour ne pas tout re-sélectionner). En revanche celle qui ne sont pas notés (celle traînant toute l'année en accès libre en fait) pourrait ne pas être cochée de base afin de ne pas les dé-sélectionner à chaque fois qu'on veut afficher aux élèves leur note.

à discuter !

**Comment by benoitkugler** [comment]
Bien vu, ça semble très raisonnable en effet !

Donc je retiens :
Affichage Note -> sélectionner par défaut toutes les travaux notés

**Comment by Guigui7707** [comment]
Yes !
