### ISSUE TITLE
[prof] Affichage code classe

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#253]
En affichant le code classe depuis le site isyro à toute la classe, les dates de naissances apparaissent aux yeux de tous (les premières).
Bien sûr j'ai coupé l'écran et écrit le code au tableau, ce qui rend cette issue mineure, mais peut-être pourrions-nous flouter l'arrière ou afficher en gros le code sur l'écran (pour cacher l'arrière plan) avec une petite croix pour quitter pour le prof s'il ne veut plus le code en énorme ?

**Comment by benoitkugler** [comment]
Bonne idée en effet !

Je vais voir concrètement, mais je retiens l'idée générale : masquer les dates de naissance lors de l'affichage du code classe.

**Comment by Guigui7707** [comment]
Oui super si tu as une autre solution elle m'ira tout autant!
