### ISSUE TITLE
Arbres

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#255]
Après deux séances avec mes stmg ça va être compliqué les arbres en colonne sur isyro car présentés en ligne dans les livres. Déjà qu'ils partent dans tous les sens avec leurs branches, je n'avais jamais imaginé qu'ils pouvaient faire un arbre symétrique de part et d'autres du point de départ 😂
Alors je ne sais pas si c'est des grosses modif à faire pour toi mais j'aimerais bien voir déjà ce que ça donne à l'écran en ligne (si vraiment c'est pas pratique)

**Comment by benoitkugler** [comment]
D'accord, on change l'orientation des arbres de l'appli. élève.  

Tu as déjà attaqué le chapitre en classe ?

**Comment by Guigui7707** [comment]
Oui j'ai déjà attaqué mais je peux gagner du temps avant de leur en mettre sur isyro car ils sont lents ^^

**Comment by Guigui7707** [comment]
En fait je pense leur en donner un de mercredi 13h à jeudi 9h, je vais créer un autre exercice pour ce week-end.
Néanmoins, si cela fait trop vite pour toi ou qu'il y ait un risque que ce soit mal fait pas de soucis ils goûteront aux arbres "verticaux" et ce sera ainsi : ne te met pas la pression non plus !! Mais c'est clairement un obstacle pour eux si ça reste ainsi (et ce n'est pas la fin du monde s'ils doivent s'y confronter).
Peut-être qu'en écartant beaucoup les deux premières branches (arbres à deux niveaux et 2 issues la plupart du temps au lycée, première et term spé comme terminale STMG) en un angle de 140-150° ça peut bien rentrer malgré tout ? Puis le deuxième niveau écarté de 20-30° ? (je n'en sais rien !!)

**Comment by benoitkugler** [comment]
Je travaille dessus ce WE, j'espère pouvoir poster une mise à jour dimanche soir, ce qui voudrait dire qu'elle serait acceptée probablement mardi ou mercredi, pile à temps..

**Comment by Guigui7707** [comment]
Ok, à la seule condition que tu ne te mette pas dans le rouge ;)
