### ISSUE TITLE
[eleve] Indicateur dispense

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#256]
> L'indicateur tu veux dire l'élève voit "dispensé" (sachant qu'on le dispensera probablement après l'arrêt des notes de la feuille pour les autres de la classe)

Je me disais qu'un élève pourrait avoir 0 et être bloqué (si le prof, pour une certaine raison, n'a pas prolongé) et qu'il pourrait alors se demander si son 0 va compter ou non.
D'où l'idée dans ce cas de clarifier la situation en lui indiquant "ok tu as 0 mais il ne comptera pas"

_Originally posted by @benoitkugler in https://github.com/benoitkugler/maths-online/issues/250#issuecomment-1709041417_

**Comment by Guigui7707** [comment]
@benoitkugler

**Comment by Guigui7707** [comment]
Un zéro rouge ne semble pas afficher l'étoile à côté pour dire que l'élève est dispensé dans sa note (bien que ça compte dispensé dans la moyenne).
Exemple de Mélina ARNASALON pour le jeudi 14 septembre où je l'ai dispensé, c'est un zéro rouge car zéro essais mais pas d'étoile à côté du zéro pour dire qu'il ne compte pas.
Peut-être par ce que c'est antérieur à ta modification sur les serveurs ?
