### ISSUE TITLE
[eleve] Message right

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#259]
Quand les élèves répondent, on pourrait changer les mots de félicitations pour varier un peu, de manière aléatoire.
Ce fil peut rester ouvert et on complète si on a des idées.

A chaque fois derrière, laisser le "Ta réponse est correcte bravo !"

Actuellement : Yes !
Ajout par exemple : Félicitations !
Bravissimo !
Oui oui oui !
Mais comment fais-tu ??
Tu n'es pas là pour beurrer les tartines/pour enfiler des perles
(C'est qui le meilleur ? C'est bibi !)
(The best for ever)

_Pythagore n'a qu'à bien se tenir... (enfin là c'est fléché maths... mais on pourrait adapter suivant la matière qui l'utilise ^^)
C'est à en faire pâlir Thalès ! (idem)_

**Comment by benoitkugler** [comment]
La matière d'une question n'est (pour l'instant) pas disponible sur l'appli élève, donc s'adapter suivant la matière me semble difficile... 

Donc je propose de garder les mots "communs".

**Comment by Guigui7707** [comment]
Très bien! C'est le mieux

Dans les citations aussi, peut être une ou deux parler de maths. "Apprendre les maths c'est bien, comprendre les maths c'est mieux!"

**Comment by Guigui7707** [comment]
Peut être que ça pourrait être lié à la feuille de travail à l'avenir, si elle est estampillé maths

Mais c'est annexe.
