### ISSUE TITLE
Maniabilité prof

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#26]
Pourvoir ajouter une étiquette oubliée à toutes les questions ayant le même titre d'un coup
![Isyro](https://user-images.githubusercontent.com/105806953/170965314-a6e7fb3e-8e74-470a-af57-e91a0a942177.PNG)

**Comment by benoitkugler** [comment]
Pouvoir modifier les étiquettes en commun à un groupe de questions.
