### ISSUE TITLE
[prof, eleve] Transfert de compte

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#260]
Une élève a cassé son téléphone et donc dû réinstaller isyro sur son nouveau. Forcément, elle a perdu sa progression (d'ailleurs en passant si on fait un système de points c'est pareil on devrait gérer ça si possible, mais bon ça veut dire un compte perso je crois alors pas sûr que ce soit envisageable). Moi de mon côté j'ai re-créé un compte et je continue de la suivre sans soucis. Mais concernant sa note du trimestre c'est plus embêtant car son ancien profil à ses premières notes et le nouveau les nouvelles notes. Je ne peux pas fusionner pour le moment et ça paraît complexe à mettre en œuvre. Un ajout manuel des notes par le prof sur les sessions du trimestre qui ont disparu ? Ce problème pourrait être fréquent avec un élève qui désinstalle isyro "pour voir" ou parce qu'il pense qu'il peut la remettre plus tard. Je soumets le problème

**Comment by benoitkugler** [comment]
Ouais c'est hyper intéressant comme problématique !

En fait je crois qu'on peut envisager une "restauration du compte", car, au fond, toute la progression élève (notes, points, etc..) est stockée sur le serveur (l'app. élève n'a que la _clé_ pour y accéder). 
Donc, en passant par l'interface prof et la classe, on pourrait avoir un bouton "copier le profil élève vers un autre téléphone" pour lier une nouvelle appli à un compte existant. Le code généré serait cette fois spécifique au compte élève (donc à ne pas partager avec l'ensemble de la classe).

De manière générale, tant que le _prof_ ne supprime pas le compte élève, il n'y aurait jamais de perte de données.

Qu'en penses-tu ?

**Comment by Guigui7707** [comment]
Ce serait super ! C'est nikel même :)

**Comment by benoitkugler** [comment]
En fait, en y réfléchissant à nouveau, il y a encore une solution plus simple : ajouter un bouton (sur la liste des élèves, côté prof) pour "enlever" le bouton vert indiquant que l'élève a rattaché son téléphone à son compte.

Ensuite, il suffira de générer un code classe comme avant, et l'élève retrouvera son nom dans la liste.

**Comment by Guigui7707** [comment]
Trop bien!! C'est parfait!

**Comment by Guigui7707** [comment]
Bien joué en tout cas pour l'idée, c'est du sur mesure

**Comment by Guigui7707** [comment]
Pour les stats, je viens d'avoir ma deuxième élève de spé à qui s'est arrivé (celle-ci n'a pas perdu/changé son téléphone mais son tél s'est réinitialisé tout seul et le compte a sauté)
