### ISSUE TITLE
[prof] Suppression exception

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#261]
J'ai par erreur exempté un élève absent de la mauvaise fiche de travail, et impossible de retirer cette exception (je n'ai peut-être pas trouvé !). Il faudrait donc pouvoir !

**Comment by benoitkugler** [comment]
En effet ! En fait, il suffit d'éditer l'exception en désactivant la deadline et la dispense.
Mais ce n'est pas tellement intuitif, on va rajouter un bouton plus clair !
