### ISSUE TITLE
[prof] Statistiques notes par exercice

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#263]
Cette issue est à discuter !
Je partage juste que : sur Wims j'ai une statistiques de réussite de la classe par exercice qui me permet de reprendre l'execrice le plus raté en classe. Là pour le moment j'ai juste la note de toute la séance sur isyro. Mais en même temps je ne veux pas que la page soit surchargé c'est très bien comme elle est actuellement. Alors peut-être réfléchir, si c'est possible, à mettre un bouton sur le côté ?

**Comment by benoitkugler** [comment]
Oui, sans problème. 

Le bouton serait accessible depuis la page des notes j'imagine..

Est-ce que tu peux préciser ce que tu veux comme statistiques ? 
Pour chaque feuille, pour chaque tâche, la note moyenne sur la classe ? Veux-tu aussi le détail par questions ?

**Comment by Guigui7707** [comment]
Alors je pense que cette page peut être très adaptable par chaque prof.
J'imagine un menu "caché" où quand le prof clique dessus il ouvre une page "complexe" où il peut cocher des items pour éditer sa feuille de statistiques. Au moins chacun peut régler à son désir les paramètres. Donc dans l'idée c'est sûrement assez infini les stats qu'on peut faire sur une feuille (tentatives, moyenne, meilleure tentative, par exercice, par question, comparatif à la classe, élève unique ...). Donc ça pourrait être complété au fil des ans.

Oui pour le bouton ce serait depuis les notes à afficher (même peut-être une fois qu'on a affiché les notes comme actuellement ? ça permet d'avoir une version de base où le prof a déjà la moyenne globale. Ou directement à l'endroit où on clique sur "afficher les notes" à voir

Là sur ma demande précise : par exercice pour le moment c'est très bien. Si j'ai 4 exercices, une moyenne classe par "exercice". Comme ils ont tous 20/20 quasiment (!) il faudrait faire une moyenne **par tentatives** .. !
Maintenant en prévision c'est sûr qu'une statistique par questions internes à "l'exercice". On sait que les 3 étoiles auront moins de réussite que les 1 étoile, mais si je vois un 1 étoile avec un mauvais pourcentage c'est sûr que je reprendrais cette question puisque la base n'est pas maîtrisée facilement.
