### ISSUE TITLE
[eleve] Moyenne sur écran élève

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#265]
Je me disais que si la moyenne était affichée directement sur l'écran élève cela règlerait les problèmes de l'affichage des notes aux élèves. (j'ai des messages : combien j'ai ? surtout pour Wims ; et afficher à tous une fois par semaine n'est pas le plus facile, la fenêtre ne contient pas les 35 élèves d'un coup, après sinon c'est trop petit, et chacun peut voir la note de l'autre...)
Mais actuellement le visuel élève est GENIALE avec la barre en travaux, ou verte ou les deux. Je ne voudrais pas y toucher, elle est ergonomique aussi avec peu de place utilisée pour 5 feuilles simultanée d'afficher les unes sous les autres, c'est topissime. (si une chose était à revoir peut-être c'est le 12/12 ou 19/19 les élèves n'aimant pas trop les notes qui ne sont pas sur 20. On pourrait remplacer à terme par un pourcentage à la rigueur OU ramener sur 20 automatiquement)
Je pensais donc à un icône en haut à droite dans le bandeau "devoir à la maison" où l'élève peut cliquer pour voir sa moyenne. ça ouvrirait par exemple une sur-page en "gros" où par exemple le logo isyro apparaîtrait avec le cercle vert qui se complète à l'ouverture (ou pas ça c'est pour le style ^^) jusqu'à atteindre le % de réussite de l'élève sur TOUTES les feuilles actives que le prof note sur le trimestre par exemple. Et au centre à la place de la couronne, la note /20 de l'élève.

**Comment by benoitkugler** [comment]
Ok, ce sont d'excellentes idées !

Pour la note, on peut en effet ramener sur 20 chaque fiche, du moins dans la vue "Devoirs à la maison", et peut être garder le détail plus 'exact' dans la vue "Contenu de la feuille".

J'aime beaucoup l'idée de la page de plus pour afficher la moyenne (et l'idée d'animation est top !).
On est d'accord que "toutes les feuilles" ça correspond en fait aux feuilles de la liste "Devoirs à la maison" (c'est à dire les feuilles notées et ayant démarré) ?

Remarque : attention à la dispense : il faudra aussi la prendre en compte dans la note moyenne.

**Comment by Guigui7707** [comment]
Excellente idée pour la note sur 20 dans "devoirs à la maison" et conserver le détails dans "contenu de la feuille" !

Oui, la note correspondrait aux feuilles notées et ayant démarré !

En ce qui concerne la partie "Entraînement", comme elle n'est pas noté, je verrais bien un logo isyro (avec ou sans animation hein pas de soucis) qui indique au niveau de "Travaux d'entraînement" le pourcentage d'avancement de l'élève, tout à droite du bandeau du titre du chapitre. Après je ne sais pas s'il y a assez de place car c'est bien ergonomique comme c'est actuellement : le mieux serait au moment où l'élève déplie son chapitre. Et enfin, dans "Contenu de la feuille" maintenir le détails comme actuellement.

**Comment by Guigui7707** [comment]
@benoitkugler 

C'est parfait !
Juste, quand un élève a 20/20 la jauge se remplit puis se vide et se fige vidée. Il faudrait qu'elle soit toute verte ;)
