### ISSUE TITLE
[questions] Variante 605

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#268]
L'indication de rédaction ne parait pas hyper pertinente : peut-être la simplifier ?

(Taper variante:605 dans le champ de recherche pour y accéder rapidement)

**Comment by benoitkugler** [comment]
@Guigui7707 Qu'en penses-tu, en tant qu'auteur ?

**Comment by Guigui7707** [comment]
Oups je n'avais pas vu ton issue !
Oui en effet pas très clair ^^
Je te laisse modifier à ta guise les exos que j'ai copié sans soucis ! Il n'y a jamais vraiment eu de relecture de ma part si ce n'est le jour où j'ai créé, donc tant que je ne l'ai pas mis à mes élèves je ne repasse pas dessus.
