### ISSUE TITLE
Arbre devoirs

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#269]
Lorsque l'on est en mode élèves, sur une question d'arbre à compléter, que l'on clique sur une branche où il faut inscrire une proba, si on touche l'écran en-dehors de la fenêtre sans valider on revient au menu des devoirs c'est assez gênant (surtout si on a cliqué par inadvertance et qu'on veut revoir l'énoncé ou où on a cliqué)

**Comment by benoitkugler** [comment]
En effet, j'arrive à reproduire !
