### ISSUE TITLE
[prof] Favoris façon isy'triv

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#272]
Lors de la création d'une feuille de travail "favoris" je me dis qu'il serait intéressant de procéder comme pour la création d'un isy'triv à savoir : si toutes les questions sont issues d'un même chapitre, afficher en haut les questions restantes du même chapitre qui n'ont pas encore été insérées

**Comment by benoitkugler** [comment]
OK, c'est intéressant !
