### ISSUE TITLE
[prof] Étiquettes dupliquées

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#278]
J'essaie de modifier les chapitres des questions "rappels" de première, mais il y a un message d'erreur qui apparaît côté serveur en rouge. Je ne sais pas si c'est parce qu'ils sont actifs dans des feuilles d'exercices sur mon compte perso ? Mais ce serait étonnant !

**Comment by benoitkugler** [comment]
Je viens d'essayer avec une question et je n'ai pas eu de problème. 
Peux-tu ré-essayer de ton côté et me dire quelle est la question problématique ?

**Comment by Guigui7707** [comment]
Alors j'ai testé à nouveau, pas mieux :

C'est "Calculer une probabilité d'intersection sur un tableau", chez les Premières chapitre Rappels.
j'essaie justement d'enlever le chapitre Rappels pour le remplacer par le chapitre Probabilité Conditionnelles, en vain donc.

**Comment by benoitkugler** [comment]
Ah OK ! 

Le problème vient du fait qu'il y a déjà une étiquette Probabilité Conditionnelles dans le champ 'IsyTriv' et qu'on autorise pas deux étiquettes identiques (pour éviter les redondances, qui signalent en général une imprécision côté utilisateur).

Est-ce que modifier le chapitre et enlever l'étiquette Probabilité Conditionnelles du champ IsyTriv est une solution satisfaisante ?

**Comment by benoitkugler** [comment]
Si oui, j'ajouterai un indicateur sur la fenêtre des étiquettes pour montrer qu'on ne peut pas répéter une étiquette.

**Comment by Guigui7707** [comment]
Ah ok!! Oui c'est très bien comme solution!

**Comment by Guigui7707** [comment]
Merci :)
