### ISSUE TITLE
Musique aléa

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#280]
Je ne retrouve plus d'issue à ce sujet mais pour synthétiser :

- à terme ce serait bien que l'appli isyro envoie spontanément des musiques aléatoire,
- mais que la toute première quand ils téléchargent l'application soit l'actuelle première (comme ça cela fera un semblant d'identité), mais ensuite que ça tourne aléa
- puis bien sûr l'élève peut choisir d'enlever l'aléa etc

**Comment by benoitkugler** [comment]
J'avais ouvert #277.

Est-ce que tu tiens vraiment à ton second point ? Cela demande pas mal de travail en plus, car il faudrait différencier deux modes : première utilisation / utilisation normale.

Personnellement, je garderais bien le status quo, qui rempli les deux autres points. Qu'en penses-tu ?

**Comment by Guigui7707** [comment]
Oui on annule le deuxième point sans problème ! Si c'est complexe comme je ne me rends pas compte tu fais bien de me dire!

**Comment by benoitkugler** [comment]
Super, merci :)
