### ISSUE TITLE
[prof] Listing

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#283]
S'il est possible d'ajouter :

binom(k;n) renvoie le nombre de combinaisons de k parmi n

dans les fonctions usuelles des paramètres aléatoires (je te laisse être plus précis que moi mathématiquement ^^)

**Comment by benoitkugler** [comment]
Il me semble qu'il y a déjà une entrée pour ça, depuis la version 1.7.4 ?

**Comment by Guigui7707** [comment]
Oui en effet, sorry !!

**Comment by Guigui7707** [comment]
Je cherche à créer un exercice qui calculer P(X<=k) mais sans les boucles je n'y arrive pas.. si ce n'est au cas par cas avec des valeurs de k petites (max 5 disons). As-tu une idée pour me débloquer ? Je ne veux pas créer des fonctions pour en créer.

**Comment by benoitkugler** [comment]
> Je cherche à créer un exercice qui calculer P(X<=k) mais sans les boucles je n'y arrive pas.. si ce n'est au cas par cas avec des valeurs de k petites (max 5 disons). As-tu une idée pour me débloquer ? Je ne veux pas créer des fonctions pour en créer.

Hum en effet, je ne crois pas qu'on puisse calculer ça actuellement. Une façon de faire serait d'ajouter une fonction somme. Par exemple,
sum(k; 1; n; k^2) calculerait la somme des carrés de 1 à n. 
Tu pourrais l'utiliser à la place d'une boucle.
Qu'en penses-tu ?

**Comment by Guigui7707** [comment]
Oui ce serait une bonne alternative !
