### ISSUE TITLE
Option partage de question

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#29]
Quand je clique sur "partager" l'icône ne passe pas en bleu et la coche ne va pas à droite malgré l'annonce "bien pris en compte"
<img width="786" alt="isyro" src="https://user-images.githubusercontent.com/105806953/171265005-61e8713f-1fa7-4cb5-9e66-fd79b4125550.PNG">

**Comment by Guigui7707** [comment]
(c'est mieux maintenant : en fermant les questions présentes dans le titre puis en déroulant de nouveau, l'intitulé "modification enregistrée" disparaît assez régulièrement et permet donc de cocher le suivant)

**Comment by benoitkugler** [comment]
En attente de #27, qui va surement modifier cette interface.
