### ISSUE TITLE
[prof] Perfectionnement visuel lancement travail à la maison

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#290]
Il serait sympa de colorer une feuille de travail notée ET active, en un coup d'oeil en passant sur la page on peut voir lesquelles sont actuellement actives ou non.

C'est du luxe bien sûr

**Comment by benoitkugler** [comment]
OK, intéressant !

On est bien d'accord qu'on parle de la page prof ?

**Comment by Guigui7707** [comment]
Yes c'est ça :)
