### ISSUE TITLE
[server/expression] Réponse non acceptée

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#295]
Le développement de 3(11/7 *x+13/2), si l'élève écrit 33*x/7+39/2 n'est pas compté juste. ça me paraît correct non ? Ou je dois leur préciser d'écrire toujours le x en dernier et de mettre des parenthèses sur la fraction ? Je ne me souviens plus..

**Comment by benoitkugler** [comment]
Non tu as bien raison, il y avait un vrai bug !
