### ISSUE TITLE
[prof/editor] Preview : Correction ceintures de calculs 

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#310]
@benoitkugler 
Le visuel de la correction est désactivée pour les questions crées sous "ceintures de calculs"

**Comment by Guigui7707** [comment]
Tout comme la duplication d'une question (intérêt plus relatif c'est vrai en principe ici)

**Comment by benoitkugler** [comment]
> @benoitkugler
> Le visuel de la correction est désactivée pour les questions crées sous "ceintures de calculs"

En effet. Je n'étais pas sur de comment l'intégrer côté élève. Quand est-ce qu'on l'affiche ? Un bouton en cas d'erreur ?

**Comment by benoitkugler** [comment]
> Tout comme la duplication d'une question (intérêt plus relatif c'est vrai en principe ici)

Je me demandais si c'était vraiment utile. Tu as un cas où tu voulais dupliquer une question ?

**Comment by Guigui7707** [comment]
Pour la duplication en effet ça ne doit pas être utilisé si c'est bien codé. Je trouverais utile pour pas recopier à chaque fois l'énoncé "développer et réduire l'expression suivante" avec le format (gras) ainsi que pour conserver les variables sur le côté sans à chaque fois les recopier.

Pour le visuel je pensais pour le moment uniquement au côté prof, pour voir la correction codée. Pour l'élève on en reparle d'ici septembre !
