### ISSUE TITLE
Déselection des isy'triv

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#322]
Quand je décoche un isy'triv à ma 2GT1 que j'avais préalablement coché, j'ai beau enregistré ça ne l'enlève pas.

**Comment by Guigui7707** [comment]
+ j'en ai créé deux que je ne vois plus sur l'interface prof dans isy'triv (révisions devoir commun aléatoire et calculs) mais ils sont pourtant bien conservé sur l'appli élèves en accès libre (je les avais paramétré pour, puis en modifiant leur nom avec un chiffre devant pour les faire remonter dans la liste côté élève ils ont disparus de ma base mais sont bien chez les élèves sous leur ancien nom)

**Comment by benoitkugler** [comment]
> Quand je décoche un isy'triv à ma 2GT1 que j'avais préalablement coché, j'ai beau enregistré ça ne l'enlève pas.

En effet, je peux reproduire le bug !

**Comment by benoitkugler** [comment]
> * j'en ai créé deux que je ne vois plus sur l'interface prof dans isy'triv (révisions devoir commun aléatoire et calculs) mais ils sont pourtant bien conservé sur l'appli élèves en accès libre (je les avais paramétré pour, puis en modifiant leur nom avec un chiffre devant pour les faire remonter dans la liste côté élève ils ont disparus de ma base mais sont bien chez les élèves sous leur ancien nom)

J'ai l'impression que l'étiquette MATHS a été enlevé des questions, donc il n’apparaît plus dans la catégorie MATHS

**Comment by benoitkugler** [comment]
@Guigui7707 Si à l'occasion tu peux vérifier que le problème a disparu ?

**Comment by Guigui7707** [comment]
C'est vérifié ça marche ! Merci!
