### ISSUE TITLE
Bug inscription compte prof

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#33]
Débloquer l'inscription prof afin de pouvoir créer nos propres trivial et rendre plus lisible la base trivial admin

![image](https://user-images.githubusercontent.com/105806953/172054727-ed538e5d-039e-4e74-a457-f055363bfe1c.png)

**Comment by benoitkugler** [comment]
Problème corrigé.

**Comment by Guigui7707** [comment]
J'ai vu, merci c'est génial !
