### ISSUE TITLE
Récupération mot de passe

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#333]
Pour le mot de passe, que je clique sur le lien fourni ou que je relance une page isyro moi-même, dans les deux cas le code fourni 61538938 est "incorrect" (je ne peux donc plus me connecter à mon compte guillaume.lebrat@gmail.com )

_Originally posted by @Guigui7707 in https://github.com/benoitkugler/maths-online/issues/332#issuecomment-2068670629_

**Comment by benoitkugler** [comment]
Je viens d'essayer et je n'ai pas problème avec ce mot de passe. 

Est-ce que tu peux ré-essayer de ton côté ?

**Comment by Guigui7707** [comment]
C'est tout bon ça fonctionne !
Mea culpa, ça devait venir de moi... j'ai copié collé le code et je crois que ça prend un espace automatique quand je colle... sorry
