### ISSUE TITLE
Suppression question compte perso

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#334]
J'ai une message d'erreur rouge quand j'essaie de supprimer une variante d'une question depuis mon compte personnel (bandeau rouge, impossible à supprimer). La question n'est pas partagée depuis le compte administrateur, elle avait été créé depuis mon compte perso. Manip faite depuis Firefox.

![image](https://github.com/benoitkugler/maths-online/assets/105806953/173a6447-8104-441f-a646-9d318de74f26)

**Comment by benoitkugler** [comment]
La question est utilisée dans une tâche (via son groupe de question). Il faut donc d'abord supprimer la tâche avant de supprimer la question.

Cela devrait être explicité correctement à l'utilisateur.

**Comment by benoitkugler** [comment]
Correction publiée. @Guigui7707  Peux-tu vérifier que le message est plus clair maintenant ? Merci !

**Comment by Guigui7707** [comment]
C'est PARFAIT ! Merci beaucoup !
