### ISSUE TITLE
[eleve/trivial] Icône guilde sur isytriv

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#335]
L'icône de la guilde est affichée à côté du nom du joueur lorsque nous sommes dans la salle d'attente d'une partie d'isytriv, mais elle n'y est pas dans la partie classement et dans l'affichage final du score. Je me dis que ça pourrait être bien de mettre en valeur cette "identité" du joueur sur ces zones-là ? Dis-moi ce que tu en penses.

**Comment by benoitkugler** [comment]
Complètement d'accord !
