### ISSUE TITLE
Création d'une fonction qui simplifie les fractions

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#34]
L'ordonnée du point A dans la question pourrait être simplifié automatiquement (il est calculé en fonction de réponses prédéfinies au début pour simplifier la création de question "basique" ; "classique" et "expert")

<img width="928" alt="isyro" src="https://user-images.githubusercontent.com/105806953/172057387-dd349dd4-e2ac-48c1-b005-8c371c72c1f2.PNG">

**Comment by benoitkugler** [comment]
J'ai travaillé sur ça et ça va arriver dans la prochaine version ;)
(Mais il faut synchroniser avec une mise à jour de l'appli, donc j'attends la semaine prochaine)

**Comment by Guigui7707** [comment]
Génial !!! Ça va vraiment rendre service ! Car là je galère à faire des
fractions qui ne se simplifient pas 😅

Le dim. 5 juin 2022 à 22:22, Benoit KUGLER ***@***.***> a
écrit :

**Comment by Guigui7707** [comment]
Encore quelques simplifications qui ne s'opèrent pas, deux dans cet exemple.
A moins qu'il ne faille utiliser une fonction spéciale lors de la création de la variable qui simplifie automatiquement ?

![Uploading isyro.PNG…]()
