### ISSUE TITLE
[prof/ceintures] Dupliquer une question

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#340]
Je viens de voir que contrairement à l'interface "questions" de base, il m'est impossible de dupliquer une question à l'intérieur du niveau "jaune", "développement" par exemple pour ne pas remettre mes paramètres à chaque fois ainsi que les blocs, idem pour les corrections. Je ne sais pas si c'est possible de faire ça ?

**Comment by benoitkugler** [comment]
Oui c'est complètement possible !
