### ISSUE TITLE
[eleve] Enregistrement progression ceinture élève 

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#343]
Lorsque le compte isyro n'est pas rattaché à une classe, les ceintures repartent à zéro chaque jour. La progression n'est pas enregistré je pense 
Pas encore testé lorsque l'appli est rattachée à une classe!

**Comment by benoitkugler** [comment]
Oui, c'est le comportement attendu actuellement.

Pour permettre l'enregistrement, il faudrait à mon avis un système de compte non rattaché à une classe.

**Comment by Guigui7707** [comment]
oups ok, merci du rappel, très bien comme ça !

**Comment by Guigui7707** [comment]
Je viens de relier mon tél à une de mes classes pour bénéficier de l'enregistrement de la progression ceinture, mais j'ai de nouveau un message d'erreur quand je lance un parcours "seconde"

**Comment by benoitkugler** [comment]
Ah ! En effet, j'ai un bug aussi.

**Comment by benoitkugler** [comment]
Problème de configuration de la base de données réelles. C'est réglé normalement, je ferme le fil. Tu peux le rouvrir si le bug persiste de ton côté.
