### ISSUE TITLE
Ajout valeur de x basée sur une variable

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#43]
Pouvoir ajouter une valeur de x pour le champ de réponse élève d'une fonction qui dépend d'une variable, afin de s'arranger pour établir une division voulue qui donnera toujours une image entière.

<img width="925" alt="isyro" src="https://user-images.githubusercontent.com/105806953/173185187-1d8be245-2bb0-4889-a6de-02a14df53078.PNG">

**Comment by benoitkugler** [comment]
Et oui, c'est assez logique finalement, comme la contrainte "ordonnée entière" est très forte, il faut permettre plus de contrôle sur les "x"...

**Comment by benoitkugler** [comment]
Il y a un détail à régler : pour les valeurs de x qui sont des expressions, on ne pourra plus les trier automatiquement par ordre croissant (par sur l'éditeur en tout cas, puisque la valeur est aléatoire).
Cela entraîne deux questions : 
- ou placer les expressions ? peut-on toujours trier ? est-ce que un tri de la forme -1, 0, 3, x, y fait sens ? Pas vraiment si x est censé être entre 0 et 3 non ?
- une fois les valeurs générées, on peut soit les trier automatiquement, soit vérifier qu'elles le sont et renvoyer une erreur sinon. 
(Les deux questions sont liées : c'est soit manuel pour les deux, soit automatique pour les deux).

Je pense que l'option tri automatique dans les deux cas est le mieux, reste à trouver sous quelle forme on affiche les listes contenant des expressions.

**Comment by benoitkugler** [comment]
Conclusion : Affichage manuel côté prof + tri automatique à la génération
