### ISSUE TITLE
Affichage : possibilité de parfaire ?

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#44]
Je ne vois pas comment éviter ce genre d'affichage +-
<img width="696" alt="isyro" src="https://user-images.githubusercontent.com/105806953/173204263-d99f5b9d-0e44-453e-9952-7af8ef242ef9.PNG">

**Comment by benoitkugler** [comment]
Ah oui, encore un cas d'expression à simplifier. Je vais ajouter le cas -1 * b => -b

**Comment by Guigui7707** [comment]
C'est quasi parfait, cela ne se produit plus que pour la variable située en début d'expression :
<img width="698" alt="isyro" src="https://user-images.githubusercontent.com/105806953/176004098-c371e299-f701-4d0a-9034-25b10b46bf79.PNG">

**Comment by benoitkugler** [comment]
Ca devrait être corrigé là aussi.
