### ISSUE TITLE
Création d'une fonction supplémentaire

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#46]
J'aurais besoin dans le cadre d'au moins un exercice d'une fonction qui renvoie la partie entière d'un réel.

**Comment by benoitkugler** [comment]
Je crois que round(x - 1/2; 0) fais l'affaire. Cela dit, comme c'est assez moche, comme expression, on peut aussi ajouter une fonction dédiée.

**Comment by Guigui7707** [comment]
Ah non merci pour l'astuce ! Je n'y avais pas pensé c'est très bien aussi :)
