### ISSUE TITLE
Préfixe justement fixe devant les propositions QCM

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#5]
Pouvoir fixer devant les réponses d'un QCM un préfixe (exemple : f(x) ; g(x) ; h(x) ; k(x)) qui donc ne bouge pas (f toujours tout en haut) tandis que les réponses (3x-1 ; 2x+5 ; 6x-1 ; x²) continuent d'être réparties aléatoirement
<img width="693" alt="isyroBUG" src="https://user-images.githubusercontent.com/31929422/169967338-4c15deac-6b6d-4048-91b8-3ca254460756.png">
.

**Comment by benoitkugler** [comment]
@Guigui7707 Pourquoi pas ! On est d'accord que ça évite juste de recopier le préfixe sur toute les lignes ? Ce serait donc essentiellement un raccourci ?

**Comment by Guigui7707** [comment]
@benoitkugler Ce serait plutôt pour éviter que les fonction s'appellent toutes k(x) par exemple ici. Simplement car dans un même exercice on évite deux fonctions différentes de même nom, c'est tout... Donc plutôt rien de base mais possibilité d'écrire f(x) g(x) etc sur chaque ligne, sans que f(x) g(x) etc changent de ligne d'une question à l'autre (le nom n'est pas relié à l'expression de la fonction en fait)
