### ISSUE TITLE
Bug de codage que je ne trouve pas...

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#51]
Une fois sur 5 j'ai ce message d'erreur mais comme la question n'est pas générée je ne trouve pas mon erreur de conception..
<img width="934" alt="isyro" src="https://user-images.githubusercontent.com/105806953/173634345-f94ef9a1-82d2-4348-8518-9bc18e5f9e0b.PNG">

**Comment by benoitkugler** [comment]
Il s'agit d'un veritable bug côté serveur, que j'arrive à reproduire.
