### ISSUE TITLE
Etiquettes

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#56]
Dans l'optique de créer des questions tout niveau (première, terminale, sup), mettre des étiquettes roses par exemple "2nde" ; "1ère" ; "terminale" ; "bac+1" sur le style des étoiles qui ont une couleur qui diffèrent du reste.
Voir aussi peut-être plus tard pour une dernière couleur pour "Lire" ; "Déterminer" ; etc

**Comment by benoitkugler** [comment]
Classe unique par question
