### ISSUE TITLE
ordre QCM

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#57]
Nous avions définie de ne pas bouger les réponses d'un QCM (je revalide) ; mais étonnamment elles ne se présentent pas selon l'ordre des choix définis dans le bloc. Ce serait bien de les ordonner, ça permet de "trier" en faisant la question, ici ça me paraît important de mettre les ensembles d'une manière "crescendo"
<img width="695" alt="isyro" src="https://user-images.githubusercontent.com/105806953/174761594-952158c6-48d0-4cdc-8f19-27818fe0aeb8.PNG">

**Comment by Guigui7707** [comment]
Je suppose que ce bug est lié au problème (voir ci-dessous, je dois écrire Choix 2 pour que Q soit validée en "Oui" or le "Oui est rentré en premier choix !)
<img width="691" alt="isyro" src="https://user-images.githubusercontent.com/105806953/174778070-3e9baa83-4ade-4a21-80c9-54915a8bb9cc.PNG">

**Comment by benoitkugler** [comment]
Pour l'instant, conserver l'aléa. Une option pour l'activer ou non est envisageable.

**Comment by benoitkugler** [comment]
@Guigui7707 Je n'arrive finalement pas à reproduire le bug que tu avais rencontré : 

> Je suppose que ce bug est lié au problème (voir ci-dessous, je dois écrire Choix 2 pour que Q soit validée en "Oui" or le "Oui est rentré en premier choix !)

Peux-tu vérifier de ton côté si tu rencontres encore le problème ?

**Comment by Guigui7707** [comment]
Je l'ai rencontré ici de nouveau :
<img width="931" alt="isyri" src="https://user-images.githubusercontent.com/105806953/175063351-f78a3362-2adf-46a4-9f0f-04bf829294c4.PNG">

**Comment by Guigui7707** [comment]
Voici un autre exemple
<img width="931" alt="isyro" src="https://user-images.githubusercontent.com/105806953/175070723-9cbb36b9-0c38-46b2-a613-b16bbe9174a0.PNG">
