### ISSUE TITLE
Maniabilité prof : &variable& coloriage

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#59]
Passer en orange si possible le &a& sur cet exemple au moment où le deuxième "&" est écrit : MAIS à vérifier avec la convention ailleurs... car là je prends la convention texte qui est ainsi et qui s'est inscrit en moi ^^
(je ne m'attendais pas à ce que ça marche du coup)
<img width="690" alt="isyro" src="https://user-images.githubusercontent.com/105806953/175065923-9bc5d987-bad0-427c-8bac-2ca9de74fb34.PNG">

**Comment by benoitkugler** [comment]
Oui je crois que j'ai été un peu fainéant ici, il vaut mieux utiliser le même type de champ...
