### ISSUE TITLE
Choix professeur de la taille du champ de réponse élèves

### ISSUE THREAD

**Issue by benoitkugler** [benoitkugler/maths-online#6]
Le professeur pourrait choisir la taille du champ de réponse (ici le y semble bien seul sur la longue ligne, et cela génère une réponse sur deux lignes)
<img width="204" alt="isyroBUG" src="https://user-images.githubusercontent.com/31929422/169967601-bdd95c0e-3bd1-4e11-8b38-e3436da01b9e.png">
.

**Comment by benoitkugler** [comment]
@Guigui7707 En effet !

Que dirais-tu d'un ajustement automatique basé sur la bonne réponse ? 
Par exemple si `y` est l'expression réponse, on affiche (automatiquement) un petit champ, mais si la réponse est `0.456x^2 + 2x + 7` là on affiche un champ plus long.

Cela éviterait d'ajouter un paramètre supplémentaire.

**Comment by Guigui7707** [comment]
@benoitkugler  Génial !! Pas besoin de rajouter ça au prof c'est top ! Ce serait parfait :)
