### ISSUE TITLE
Aléa sur des symboles

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#63]
Serait-il possible tu penses qu'isyro valide ceci :

k=randint(1;2)
k_1=isZero(k-1)
k_2=isZero(k-2)
s=k_1*<+k_2*>

Ainsi s "vaut" < si k=1 et > si k=2

ça me paraît hautement improbable mais cela permettrait dans le chapitre des réels de pouvoir coder plusieurs cas similaire sur une seule question. Sinon pas de soucis je duplique.

**Comment by benoitkugler** [comment]
L'idée est très intéressante, mais le problème c'est que le moteur d'expression ne comprends que les expressions mathématiques valides (et pas toutes encore...)Et je ne vois pas bien comme donner un sens général à la syntaxe que tu proposes... Le 24 juin 2022 12:40, Guigui7707 ***@***.***> a écrit :

Serait-il possible tu penses qu'isyro valide ceci :

k=randint(1;2)

k_1=isZero(k-1)

k_2=isZero(k-2)

s=k_1*<+k_2*>

Ainsi s "vaut" < si k=1 et > si k=2

ça me paraît hautement improbable mais cela permettrait dans le chapitre des réels de pouvoir coder plusieurs cas similaire sur une seule question. Sinon pas de soucis je duplique.

**Comment by Guigui7707** [comment]
Oui je comprends 👍 
Très bien alors, je m'en passe sans problème !

**Comment by benoitkugler** [comment]
Généraliser les expressions pour accepter la nouvelle fonction choice(<; >; k) ou choice(A;B;C;D; randInt(1;4))

**Comment by benoitkugler** [comment]
Après réflexion, choice est renommé en choiceSymbol et randLetter en randSymbol (pour illustrer la similarité entre les deux fonctions, randSymbol étant simplement un raccourci pour choiceSymbol).
Pour choiceSymbol, des parenthèses sont ajoutées aux choix, pour repérer l'oubli du dernier argument. 
La nouvelle syntaxe est donc  : 
choiceSymbol( (A; B); k)
