### ISSUE TITLE
Affichage joli "x"

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#64]
Je crois que je rate quelque chose, mes "x" sont ne sont pas "joli" quand je les mets en $$, mais c'est peut-être réserver qu'aux formules justement ?
<img width="698" alt="isyro" src="https://user-images.githubusercontent.com/105806953/175571451-9694b2f3-3c20-40aa-89fa-3dd9f0521878.PNG">

**Comment by benoitkugler** [comment]
Ah intéressant. En fait c'est l'interaction avec le Gras qui cause ce changement (tu peux vérifier en le décochant).
Il se trouve que le moteur LaTeX, quand on lui donne le gras, change la police. 
C'est cohérent avec la convention utilisée dans la recherche par exemple, mais ça ne fait pas trop nos affaires ici.

Une solution simple c'est de ne jamais mettre le gras en LaTeX (le reste du message texte le sera, mais pas les bouts de maths). Vu que ce sont des symboles mathématiques, l'absence de gras ne doit pas être visuellement trop gênante.

**Comment by Guigui7707** [comment]
Ah oui bien sûr ! Merci je vais faire ça j'enlève le gras sur ce style de question, merci !
