### ISSUE TITLE
Message usuel écran élève

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#65]
Avant chaque activité isyro, ce serait bien de mettre un message du style : "es-tu bien muni d'une feuille, d'un stylo et d'une calculatrice ? Prends l'habitude de jouer et travailler dans les meilleures conditions de réussite possible !" et l'élève coche "OK" ou "oui".
On pourrait s'amuser à laisser ce message jusqu'à la première réponse juste de l'élève ^^

**Comment by Guigui7707** [comment]
Avec des variantes du style : 
-"as-tu bien pensé à ta triplette "stylo-feuille-calculette" pour mettre toutes les chances de ton côté ?"
- "pour réaliser une bonne recette de mathématiques, prendre un zeste de stylo, une demi-feuille de brouillon et une calculatrice bien chargée, manier le tout une bonne quinzaine de minutes et le tour est joué !"
- "as-tu bien ton triplé "stylo-feuille-calculette" pour tenter de scorer ?"
- "STOP. Vos *papiers* s'il vous plait... mes *calculs* sont formels : sans stylo, vous êtes en infraction du code des maths"
- dernière variante : 3 images, une pour chacun de ces ustensiles

**Comment by benoitkugler** [comment]
Ah excellent, je suis fan de l'idée et surtout des variants aléatoires !!!
