### ISSUE TITLE
Figure : compléments

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#66]
Je me suis aussi amusé à faire ce genre de question (ci-dessous) ! Quelques axes d'améliorations possibles, mais là encore c'est très à la marge (peut-être utilisé dans les diagrammes à moustache en première) :
- pouvoir afficher ou masquer les points créé
- pouvoir colorier une zone (comme un rectangle ici)
Dans l'optique peut-être aussi un jour de développer l'aspect "Geogebra" ou l'élève peut faire varier lui-même un point sur une figure afin de conjecturer quand les aires d'un triangle et d'un carré inscrits dans un rectangle par exemple sont égales ou autres (DM)
<img width="204" alt="isyro" src="https://user-images.githubusercontent.com/105806953/175608229-84777baa-f059-46f1-a5c2-3d47bb63ada6.PNG">

**Comment by benoitkugler** [comment]
Haha je ne pensais même pas qu'un résultat comme ça était atteignable ! Énorme !

**Comment by benoitkugler** [comment]
Couleur des points : ajouter transparent
Ajouter Zone coloriée définie par des points
