### ISSUE TITLE
Simplification -1*

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#67]
Si jamais tu trouves une solution pour cet affichage c'est volontiers, sinon je retirerai le cas Z et créerai une deuxième avec un moins devant.
<img width="929" alt="isyro" src="https://user-images.githubusercontent.com/105806953/175763757-fd93420c-638f-419c-ab5b-988af8e67dc4.PNG">

**Comment by benoitkugler** [comment]
Ca semble jouable ! :)
