### ISSUE TITLE
Nouveau champ de réponse

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#68]
Associer 3 propositions "jaunes" à 3 propositions "bleues", sans qu'il n'y ait de "fausse réponse" additionnelle = les 3 rectangles jaunes doivent s'associer chacun à un unique rectangle bleu.
Exemple : associer chaque CM au bon taux d'évolution
+200%
+100%
+50%
avec en face à ordonner
*1,5
*2
*3

Mais peut-être cela se fait-il déjà avec une astuce sous le format glisser-déposer ?

**Comment by benoitkugler** [comment]
> Mais peut-être cela se fait-il déjà avec une astuce sous le format glisser-déposer ?

C'est vrai que tu pourrais utiliser un champ Liste ordonnée et demander de mettre dans le même ordre que celui donné.
