### ISSUE TITLE
Partie élève

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#70]
Laisser le "Théo doit lancer le dé" visible sur l'écran jusqu'à ce que : le joueur ait appuyé sur "ok" OU que Théo ait lancé le dé.
Idem, laisser "A toi de lancer le dé" visible sur l'écran jusqu'à ce que : le joueur ait appuyé sur "ok" OU ait lancé le dé.

**Comment by benoitkugler** [comment]
Ouais pas bête ce serait plus clair pour tout le monde.

**Comment by Guigui7707** [comment]
Parfait!

Une dernière chose, si possible, afficher "X doit lancer le dé" ou "X réfléchit encore à la question" sur l'écran du joueur Y dès que celui-ci met "suivant" et se retrouve sur le plateau de jeu

**Comment by benoitkugler** [comment]
J'ai ouvert #76 pour ça.
