### ISSUE TITLE
Droite verticale et couleurs des segments

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#8]
Pouvoir changer la couleur d'un segment comme c'est fait pour les droites ; pouvoir ne pas mettre de légende pour des points ("aucune") ; pouvoir tracer une droite passant par deux points (à moins que j'ai loupé quelque chose) : là j'ai esquivé en créant point C et D hors écran pour ensuite construire un segment [CD].

<img width="920" alt="isyro" src="https://user-images.githubusercontent.com/105806953/170031220-71f3e301-dc6c-43c7-a8f5-5cfc4f71f8f4.PNG">

**Comment by benoitkugler** [comment]
Ajouter aussi droite verticale dans Droites

**Comment by benoitkugler** [comment]
Test
