### ISSUE TITLE
Ajout correction automatique interface questions

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#87]
Je commence à avoir envie de développer la partie réponse détaillée :)
Il faudrait ajouter un bouton "correction" ou "correction détaillée" à chaque question (partie question mais aussi partie exercice) où le prof peut coder la solution avec les valeurs de l'exercice. L'élève verra automatiquement le bouton (affiché dès que l'élève a validé sa réponse) qui, en cliquant dessus, lui permet de défiler un texte sous la question proposée avec le détail écrit.
Aussi dans la même idée, ajouter un bouton "vidéo" ou "vidéo explicative" de la notion, accessible dès l'arrivée de la question : quand l’élève clique dessus ça lui ouvre la vidéo explicative de la notion (avec d'autres valeurs fixes du coup).

L'option vidéo et correction détaillée ne devrait pas être affichée lors du trivial poursuite où le privilège de l'explication est gardée pour les autres élèves ou le prof + pour la fluidité et rapidité du jeu (qu'un élève ne passe pas 5min à essayer de comprendre en faisant patienter tous les autres s'ils jouent à la maison). Ces ajouts seraient pour les devoirs à la maison donc ! Quand les questions sont indépendantes, à voir pour les questions liées (une même question répétées 3 fois oui, mais un exercice suivi ce sera automatiquement codé par le prof je pense, au fil de l'évolution de l'exercice)

**Comment by Guigui7707** [comment]
Je pense que l'aide vidéo serait à intégrer par le professeur au sein de la question ET de son numéro précis : une même question peut traiter plusieurs cas différents et donc une vidéo pour chaque titre de question serait restrictif.
Le professeur pourrait cocher au moment de l'attribution des exercices "avec ou sans vidéo" pour que l'élève y ait accès ou non. Ce pourrait être sans lors d'entraînements à l'évaluation ou pour les évaluations, et avec lors d'exercices partie "travail à la maison"

**Comment by Guigui7707** [comment]
En réalité, les exercices liés jouent ce rôle... on pourrait aussi partir là-dessus à voir.
Quoi qu'il en soit, il faudrait ajouter une dernière étape à un exercice lié qui permette de faire un récapitulatif à l'élève de l'exercice réalisé (surtout pour que le prof puisse commenter la réponse à la dernière question de l'exercice)

**Comment by Guigui7707** [comment]
Il faut ajouter une question sans réponse attendue et avec un barème de 0 point.

**Comment by benoitkugler** [comment]
Solution acceptable :

- [ ] Ajouter une nouvelle liste de Block (optionnelle) 
- [ ] Supporter les liens hypertextes pour pouvoir ajouter une vidéo externe

**Comment by benoitkugler** [comment]
Questions indépendantes : afficher le bouton de correction sur chaque titre ligne de question dans le sommaire après la première tentative
Questions liées : afficher le bouton de correction après la première tentative
