### ISSUE TITLE
[eleve] Visuel élève : texte en gras => surbrillance

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#88]
Je trouve (à voir sur plusieurs avis) que le gras amène une légère surbrillance qui complique légèrement la lecture :
<img width="200" alt="isyro" src="https://user-images.githubusercontent.com/105806953/180955896-1b690152-b61f-4207-b84b-ab69d88cf9bf.PNG">

**Comment by benoitkugler** [comment]
Peux-tu vérifier si tu observes le même comportement sur téléphone ?
De mon côté, c'est en effet un peu flou sur navigateur, mais tout à fait correct sur téléphone.

**Comment by Guigui7707** [comment]
Oui tu as raison, c'est parfait sur téléphone, je t'avais déjà demandé je crois en plus oups :/
C'est seulement les textes "pour réaliser une bonne recette de maths" etc et les citations qui "brillent" et ne sont pas très lisibles, selon moi

**Comment by benoitkugler** [comment]
D'ac. Je vais atténuer l'effet alors.
