### ISSUE TITLE
[eleve] Aide rédaction élève

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#90]
Discuter de l'idée de mettre aussi un point d'interrogation sur l'écran élève (systématique ou suivant le choix du prof) qui synthétise les différentes notations isyro OU maintenir l'idée que dans la question le prof met le texte qu'il trouve nécessaire à la rédaction élève.
<img width="208" alt="isyro" src="https://user-images.githubusercontent.com/105806953/181196890-22ce4e35-3cb6-47cf-94b2-ed3553922671.PNG">

**Comment by benoitkugler** [comment]
Solution semi automatique : 
- déterminer les champs nécessitant une aide (Expression, Nombre, ...)
- déterminer à l'avance la liste des aides à fournir en fonction de la syntaxe 
- sélectionner automatiquement les aides à afficher

**Comment by benoitkugler** [comment]
Liste des aides : 

inf : \infty s'écrit inf
-inf: -\infty s'écrit -inf
a/b : \frac{2x+1}{-3x+7} s'écrit (2x + 1) / (-3x + 7)
x^n (n >= 2) : x^2 s'écrit x^2

**Comment by benoitkugler** [comment]
Ajouter un bouton sur le Block expression pour ajouter un champ texte pré-rempli automatiquement
