### ISSUE TITLE
[prof/editor] Création d'un outil pour classifier les exercices créé

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#92]
Ajout d'étiquette et de recherche par étiquette pour les exercices créé ? Ou autre système ?

**Comment by Guigui7707** [comment]
Possibilité de dupliquer un exercice complet (ex : utile pour les cas du signe de Delta, 3 exercices de fait sur le même modèle)

**Comment by Guigui7707** [comment]
Rendre le bouton "éditer les question" plus visible (avec un texte) OU pouvoir modifier la question dans un exercice en cliquant dessus (j'ai mis 3min à trouver comment faire perso malgré ta démo de la semaine dernière xD)

**Comment by Guigui7707** [comment]
Sur des questions liées, il semblerait que les chiffres bougent d'une question à l'autre lorsque l'on a juste

**Comment by Guigui7707** [comment]
Note : ne pas trop s'étendre sur le titre de l'exercice car affiché sur l'écran élève (c'est bien), mais style pas mettre "équation du second degré avec deux solutions xD"

**Comment by Guigui7707** [comment]
Il faudra rediscuter et clarifier la création de questions internes à la partie exercice (vont-elles sur la bibliothèque de la partie bibliothèque ?). Je ne crois pas que ce soit le cas, et il ne faut pas en effet (car les questions des exercices sont spécifiques je trouve après en voir fait quelques uns).
Mais aussi dans l'autre sens : si j'importe une question de la base de questions dans un exercice (par exemple la première) puis que je veux travailler dessus, il ne faudrait pas que ça impacte celle de la base question (je ne sais pas si c'est le cas) car souvent on veut ajouter des variables et compléter l'énoncé pour préparer le terrain pour les questions liées suivantes. Or cela serait dommageable que la question de base dans la bibliothèque soit modifiée ! Le mieux serait d'importer, de dissocier pour travailler en électron libre dessus.

**Comment by benoitkugler** [comment]
> Il faudra rediscuter et clarifier la création de questions internes à la partie exercice (vont-elles sur la bibliothèque de la partie bibliothèque ?). Je ne crois pas que ce soit le cas, et il ne faut pas en effet (car les questions des exercices sont spécifiques je trouve après en voir fait quelques uns).
> Mais aussi dans l'autre sens : si j'importe une question de la base de questions dans un exercice (par exemple la première) puis que je veux travailler dessus, il ne faudrait pas que ça impacte celle de la base question (je ne sais pas si c'est le cas) car souvent on veut ajouter des variables et compléter l'énoncé pour préparer le terrain pour les questions liées suivantes. Or cela serait dommageable que la question de base dans la bibliothèque soit modifiée ! Le mieux serait d'importer, de dissocier pour travailler en électron libre dessus.

Très bon point, ça mérite une "issue" séparée, j'ouvre #105 pour cela.

**Comment by benoitkugler** [comment]
Système de recherche et d'étiquettes.
Système de "groupe" d'exercices, avec variantes.
