### ISSUE TITLE
[prof/editor] Exercice : ajout d'un bouton "Déverrouiller"

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#93]
Sur des questions liées, il semblerait que les chiffres bougent d'une question à l'autre lorsque l'on a juste.

Pour l'interface prof, pouvoir circuler sur les questions liées non débloquées (pour éviter de résoudre l'exercice soi-même à chaque fois) : à mon avis problème réglé en proposant un bouton "afficher la réponse" au prof pour qu'il puisse valider dans la foulée. A voir car sur un exercice à 7 questions ça fera long de tout valider pour voir le visuel de la 7ème question.

**Comment by Guigui7707** [comment]
(je parle lors d'une reprise de l'exercice, car lorsque l'on avance dans l'exercice ça fige à la page où l'on a réussi à aller donc c'est bien)

**Comment by Guigui7707** [comment]
Point d'attention : quand on créé un exercice, qu'on sélectionne "questions liées" puis qu'on créé une question, cela remet à jour en "questions indépendantes"

**Comment by Guigui7707** [comment]
Point d'attention : quand on créé un exercice, qu'on sélectionne "questions liées" puis qu'on créé une question, cela remet à jour en "questions indépendantes" (uniquement la première fois)

**Comment by Guigui7707** [comment]
Point d'attention : quand on créé un exercice, qu'on sélectionne "questions liées" puis qu'on créé une question, cela remet à jour en "questions indépendantes"

**Comment by Guigui7707** [comment]
Sur des questions liées, il semblerait que les chiffres bougent d'une question à l'autre lorsque l'on a juste.

Pour l'interface prof, pouvoir circuler sur les questions liées non débloquées (pour éviter de résoudre l'exercice soi-même à chaque fois) : à mon avis problème réglé en proposant un bouton "afficher la réponse" au prof pour qu'il puisse valider dans la foulée. A voir car sur un exercice à 7 questions ça fera long de tout valider pour voir le visuel de la 7ème question.
Une solution pourrait être que le prof code en "questions indépendantes" puis à la fin passe en "questions liées" finalement.

**Comment by Guigui7707** [comment]
Idée pour la deuxième remarque :  Une solution pourrait être que le prof code en "questions indépendantes" puis à la fin passe en "questions liées" finalement.

**Comment by benoitkugler** [comment]
> Point d'attention : quand on créé un exercice, qu'on sélectionne "questions liées" puis qu'on créé une question, cela remet à jour en "questions indépendantes"

Cela est lié au fait qu'il faut sauvegarder les modifications je pense. Ce sera résolu par #80.

**Comment by benoitkugler** [comment]
Ajouter une option "Déverrouillage" pour permettre de circuler librement dans les exos liés.

**Comment by benoitkugler** [comment]
Résolu par #158
