### ISSUE TITLE
[eleve] Partie exercices, questions liées 

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#94]
C'est un peu surprenant de passer à la question suivante quand on a eu juste, on ne sait pas bien ce qu'il se passe. Aussi, ça affiche quand c'est faux mais pas quand c'est juste : ce serait bien je pense d'ajouter un écran "bravo bonne réponse !" deux secondes ou un bouton "poursuivre la série"

**Comment by Guigui7707** [comment]
"poursuivre l'exercice"

**Comment by benoitkugler** [comment]
Excellent !
