### ISSUE TITLE
[eleve] Visuel élève menu déroulant

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#95]
Pas forcément à tenir compte, mais en jouant quand il y a deux QCM menu déroulant on ne distingue pas trop qu'il y a deux réponses possibles, voir même qu'il faut cliquer pour dérouler le menu. Un petit triangle vers le bas dans un coin ou au centre de la case pour le spécifier ?

**Comment by benoitkugler** [comment]
Bonne idée, je pense qu'ajouter un texte "Choisir" dans la case devrait faire l'affaire.

**Comment by Guigui7707** [comment]
Parfait !
