### ISSUE TITLE
[questions] Création bloc réponse : Tableau de signe

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#96]
Réponses "tableau de signes" pour que l'élève complète, exactement sur le même principe que les tableaux de variations (combien de racines ? puis tableau adapté)

**Comment by benoitkugler** [comment]
D'ac, logique.
Un détail : est ce que le terme "racine" est officiel ? De mon côté, j'utilise plutôt une périphrase. Alternatives possibles : zéro (de la fonction) ? Changements de signe ? (Techniquement c'est incorrect mais il me semble qu'on ne présente que des fonctions où changement de signe et annulation sont équivalents)

**Comment by Guigui7707** [comment]
Hum intéressant je ne savais pas! Pour la convexité il existe des fonctions qui ne changent pas de signe autour de leur "zéro" en dérivée seconde. Donc pas changement de signe je pense, plutôt zéro s'il faut choisir
Une racine me semble-t-il est une valeur qui annule un polynôme (je viens d'aller vérifier, appelé aussi zéro donc les deux sont bons)
