### ISSUE TITLE
Création code fixe démo

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#97]
Plusieurs me demandent des nouvelles d'isyro (parmi ceux qui prient auxquels j'ai soumis le projet) : serait-il possible de créer une version test figée avec une code 255.etc.nombre de joueurs comme tu avais fais pour les pourcentages mais pour le trivial EXEMPLE déjà présent dans la base ? Ce sont des additions et multiplications simples pour pouvoir tester le jeu justement sans galérer pour les non matheux :)

**Comment by benoitkugler** [comment]
Oui, très bonne idée ! 
Est-ce que le nombre 255 est important ?

**Comment by Guigui7707** [comment]
Non pas du tout, c'était pour aider à comprendre que c'était sur le style du premier que tu m'avais fait :)

**Comment by Guigui7707** [comment]
Si tu peux me signifier quand ce sera aussi disponible sur Apple sans passer par TestFlight ce sera volontiers :)

**Comment by Guigui7707** [comment]
L'exercice n°10 "exemple exercice questions liées" est prêt pour être la démonstration de sa catégorie (sur le même principe que le trivial poursuite "exemple")

**Comment by benoitkugler** [comment]
Résolu par 53dce70ab25daee581707f8727d0df26eb107a9e
