### ISSUE TITLE
Variables sur légende figure

### ISSUE THREAD

**Issue by Guigui7707** [benoitkugler/maths-online#99]
Si c'est possible d'accepter aussi les variables pour les légendes de figures (pour y mettre des valeurs chiffrées) ce serait top!
<img width="676" alt="isyro" src="https://user-images.githubusercontent.com/105806953/182812165-40891bc1-dfed-4b27-bea9-92d981295a27.PNG">

**Comment by benoitkugler** [comment]
La modification a07f1d7d880adff52f6bce2b45587c68fedfcb1c a aussi réglé ce problème.
